### ISSUE TITLE
sender_localpart is allowed to match namespace regex

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/synapse#1004]
This registration file should cause startup to fail because the HS has no way to tell between the bot and users on the HS.

``` yaml
namespaces:
  users:
    - exclusive: true
      regex: '@irc_.*:localhost:8480'
...
sender_localpart: irc_federatedbot
```
