### ISSUE TITLE
Retention Policy does not clear files

### ISSUE THREAD

**Issue by NHAS** [matrix-org/synapse#10159]
### Description

The homeserver that I am running has a server wide retention policy set to clear data after 5 days or 14 days maximum. However old files are not cleared. 

```
retention:
  # The message retention policies feature is disabled by default. Uncomment the
  # following line to enable it.
  #
  enabled: true

  # Default retention policy. If set, Synapse will apply it to rooms that lack the
  # 'm.room.retention' state event. Currently, the value of 'min_lifetime' doesn't
  # matter much because Synapse doesn't take it into account yet.
  #
  default_policy:
    min_lifetime: 1m
    max_lifetime: 5d

  # Retention policy limits. If set, a user won't be able to send a
  # 'm.room.retention' event which features a 'min_lifetime' or a 'max_lifetime'
  # that's not within this range. This is especially useful in closed federations,
  # in which server admins can make sure every federating server applies the same
  # rules.
  #
  allowed_lifetime_min: 1m
  allowed_lifetime_max: 14d
```

### Steps to reproduce

- Set retention policy
- Share a file in a chat room and then wait until the retention policy should apply

I would expect files along with all events (except username changes/avatar changes) to be cleared after the specified time.

### Version information

- **Homeserver**: Another homeserver

- **Version**: 1.35.1+bionic1

- **Install method**: Package manager

- **Platform**: Ubuntu 18.04 LTS, Postgres
