### ISSUE TITLE
no debug logged to syslog?

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/synapse#10607]
This log config only logs debug to file and not to syslog.

```
version: 1

formatters:
    precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    syslogprecise:
        format: 'matrix-synapse %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    syslog:
        format: 'matrix-synapse %(message)s'

filters:
    context:
        (): synapse.logging.context.LoggingContextFilter
        request: ""

handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
        filename: /data/homeserver.log
        maxBytes: 104857600
        backupCount: 10
        filters: [context]
        encoding: utf8
    syslog:
        class: logging.handlers.SysLogHandler
        formatter: syslogprecise
        address: '/dev/log'
    console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]

loggers:
    ldap3:
        level: WARNING
    ldap_auth_provider:
        level: WARNING
    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO

root:
    level: DEBUG
    handlers: [syslog,file]

disable_existing_loggers: false
```

using version
git clone -b federation_through_proxy https://github.com/dklimpel/synapse/
