### ISSUE TITLE
can't disable user_directory (privacy issue)

### ISSUE THREAD

**Issue by felixx9** [matrix-org/synapse#11266]
I installed my first synapse via this ansible deploy project.

Due to privacy reasons I want to disable the user_directory:
```
matrix_synapse_configuration_extension_yaml: |
  user_directory:
    enabled: false
    search_all_users: false
```
With two brand new users on a brand new install: As soon I enter the "@"-sign, I get suggestions:

![Screenshot from 2021-11-06 02-14-55](https://user-images.githubusercontent.com/51174875/140593054-5e9f8aff-337a-460e-90d1-448b17bbea1d.png)

On my existing "standard" deploy that's not the case:
```
# User Directory configuration
#
# 'enabled' defines whether users can search the user directory. If
# false then empty responses are returned to all queries. Defaults to
# true.
#
# 'search_all_users' defines whether to search all users visible to your HS
# when searching the user directory, rather than limiting to users visible
# in public rooms.  Defaults to false.  If you set it True, you'll have to
# rebuild the user_directory search indexes, see
# https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md
#
user_directory:
  enabled: false
  search_all_users: false
```

![Screenshot from 2021-11-06 02-19-41](https://user-images.githubusercontent.com/51174875/140593097-08fd2b9c-9f20-4807-b868-d6d2b6fc92d0.png)

I also tried the settings
```
limit_profile_requests_to_users_who_share_rooms: true
include_profile_data_on_invite: false
```
no success.

all ansible details already discussed here: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1381

Any other ideas?
