### ISSUE TITLE
Configuration files should be more templatable in the standard images

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#11489]
**Description:**

In container driven worlds, when simple templating of a config file is desired, there are a few ways to go about it, but they're not 100% easy to use, for example cases like these require extending the synapse container with scripts or even extra docker containers:

 - a live deployment where the database credentials cycle automatically and are configured based on environment variables (possibly sourced from a kubernetes or other secret)
 - complement needing to bundle it's own templating of configuration: https://github.com/matrix-org/complement/blob/master/dockerfiles/synapse/homeserver.yaml & https://github.com/matrix-org/complement/blob/master/dockerfiles/synapse/start.sh
 - a stateless container that doesn't provide the ability to write config file changes to disk
 - test servers that are spun up on demand for non-technical users, wanting minimal configuration options.

A while ago we were able to provide templating via some fixed environment variables but removed that due to maintenance complexity as everything needed to be a environment variable.

We have the debian system that templates from debconf: https://github.com/matrix-org/synapse/blob/develop/debian/manage_debconf.pl

We currently have the --generate-config option which templates out synapse configuration based on environment variables, but only a limited number of values are supported https://github.com/matrix-org/synapse/blob/develop/docker/start.py#L130 and it relies on being able to write the generated result back out and have it persisted.

We can also currently use a conf.d/ type configuration, and be responsible for writing parts of the config out from different sources, but that gets complicated if the configuration is nested, eg sharing the database password from one source and the database hostname from another requires merging two trees of configuration.

We could create some specific syntax for use in the config file, eg `hostname: "${ENV['POSTGRES_HOST']}"` to allow values to be read from environment variables, which might deal with a lot of the cases - provide a static config file and specify which two or three secrets are to be provided.

Or maybe we could get value from loosening up the existing `--generate-config` templating so it could run before every start (so doesn't run and exit) but only templates the configuration files; not the other files it currently makes.

We find ourselves repeating these slight configurations in a lot of tiny built images, and I wonder if we could replace them with a single standard templating option.

I'm not sure of the right answer here; but it's currently painful to have to reimplement the templating of synapse config files again and again in each usecase, so creating this issue to see if we can make something simpler here.

**Comment by reivilibre** [comment]
See also: https://github.com/matrix-org/synapse/issues/11203

**Comment by benbz** [comment]
> See also: #11203 (configuration fragments should merge recursively) — though doesn't really address all the points here.

If the solution to this issue is arbitrary templating (e.g. env vars for any value), in my mind that would also solve the problems the #11203 is trying to solve - e.g. there could be a single config file and the DB connection pool size / worker name / etc settings could be templated in

**Comment by woojoo666** [comment]
one possible method may be to use the same method that [mautrix bridges](https://github.com/mautrix/facebook/pull/117/files) uses, which is just to accept an environment variable for any configuration parameter

```python
class Config(BaseBridgeConfig):
    def __getitem__(self, key: str) -> Any:
        try:
            return os.environ[f"MAUTRIX_FACEBOOK_{key.replace('.', '_').upper()}"]
        except KeyError:
            return super().__getitem__(key)
```

So for some configuration like `database.args.password`, you would just provide an environment variable `DATABASE_ARGS_PASSWORD`.

I think this would be pretty quick to implement, and would make it vastly easier to use docker compose with Synapse, as well as making it viable to version-control the config files without worrying about leaking sensitive secrets.

However I suspect this sort of extreme flexibility may lead to many more bugs and user error. For example, what happens if Synapse adds a config that happens to match a common environment variable, like `path` or `home`. So perhaps we should also maintain a whitelist of accepted environment variables, so that it is clear to both developers and users which environment variables can be configured. And in the beginning we can keep the whitelist small to reduce bugs and maintenance work.

**Comment by woojoo666** [comment]
I was looking into the [legacy `migrate_configs` command](https://github.com/matrix-org/synapse/blob/develop/docker/README.md#legacy-dynamic-configuration-file-support) that was carried over from the previous method of generating the config from environment variables that @michaelkaye mentioned (for converting environment variables to the config). It looks like the command takes in the [/conf/homeserver.yaml](https://github.com/matrix-org/synapse/blob/v1.49.2/docker/conf/homeserver.yaml) jinja template and then transforms it according to runtime environment variables. I think we might be able to re-purpose this method.

Maybe we can allow the user to provide their own jinja template from which the config file is dynamically generated (using the environment variables supplied by the user during runtime). So the user gets to define both their own environment variables and how they are used in the configuration. And this way, Synapse doesn't have to worry about providing a template where everything is an environment variable, because the user chooses how customizable their template is.

**Comment by richvdh** [comment]
@benbz, @woojoo666: regarding the ability to specify values for any setting via an env var, see https://github.com/matrix-org/synapse/issues/5518#issuecomment-586288446. In particular, how would you represent a list of listeners, each with their own set of sub-options? At the moment this looks like:

```yaml
listeners:
  - port: 8448
    type: http
    tls: true
    resources:
      - names: [client, federation]
        compress: false

  - port: 8008
    tls: false
    bind_address: ''
    type: http
    x_forwarded: true

    resources:
      - names: [client, federation, consent]
        compress: false

    additional_resources:
      "/_matrix/saml2/pick_username":
        module: matrix_synapse_saml.pick_username_resource

  - port: 9093
    type: http
    resources:
      - names: [replication]

  - port: 9000
    bind_address: 127.0.0.1
    type: manhole

  - port: 9111
    bind_address: ''
    type: replication

  - port: 9050
    type: metrics
```

And let's take the removal of `migrate_config` elsewhere. That is very much meant as a migration tool for people with old setups, not something to be used day-to-day.

**Comment by benbz** [comment]
> @benbz, @woojoo666: regarding the ability to specify values for any setting via an env var, see [#5518 (comment)](https://github.com/matrix-org/synapse/issues/5518#issuecomment-586288446). In particular, how would you represent a list of listeners, each with their own set of sub-options?

Sorry I missed this question. For my purposes I don't need that level of functionality (though I'm sure if it was available I'd make use of it), I just need simple value substitution.

**Comment by richvdh** [comment]
@benbz:

> I just need simple value substitution.

an example of what you're envisaging here would be super helpful.

**Comment by benbz** [comment]
```yaml
worker_app: synapse.app.generic_worker
worker_name: <WORKER_IDENTIFIER>
database:
  name: psycopg2
  args:
    application_name: <WORKER_IDENTIFIER>
    ....
```

Where `<WORKER_IDENTIFIER>` will be passed in (e.g. via env vars) as a distinct value for every process that uses this config fragment. For my use-case in Kubernetes I then only need to create different config fragments per worker-type rather than one for every worker instance
