### ISSUE TITLE
[FEATURE] OIDC 'user_mapping_provider': Support for more complex data structure 

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#11670]
It would be very helpful if the `user_mapping_provider` of `OIDC` would support the mapping of a bit more complex data structure.

For instance if the returned data would not be `user.id` but `user.data.id`.

So instead of ...
```
    user_mapping_provider:
      config:
        subject_claim: "id"
        localpart_template: "{{ user.id }}" 
        display_name_template: "{{ user.name }}"
        email_template: "{{ user.email }}"
```

this ...

```
    user_mapping_provider:
      config:
        subject_claim: "id"
        localpart_template: "{{ user.data.id }}" 
        display_name_template: "{{ user.data.name }}"
        email_template: "{{ user.data.email }}"
```

This would be more flexible.

**Comment by clokep** [comment]
This sounds similar to #8511, although a bit more generic.

I think what you're wanting will actually work fine if the userinfo that gets returned of that form though, e.g.:

```json
{
    "user": {
        "data": {
            "id": "foo"
        }
    }
}
```

The other option is to create a separate mapping provider, which is why they're pluggable.

**Comment by reivilibre** [comment]
I don't think I understand how changing `user` to `user.data` is making anything more flexible, but I'm not that knowledgeable about OIDC — sorry.

Does clokep's comment above address the problem, or is there something else needed?

**Comment by menturion** [comment]
The REST api of the OIDC/Oauth2 user info endpoint might respond with a more structured data, like: 

User info endpoint response (example # 01):
```
{
    "data": {
        "user_id": "1056",
        "name": "John Doe",
        "email": "email@example.com"
    },
    "message": {
        ...
    },
    "status": {
        ..
    }
}
```

Currently, the `user_mapping_provider` seems to require the user object to be returned (example # 02) like this

```
{
    "user_id": "1056",
    "name": "John Doe",
    "email": "email@example.com"
}
```

so that the mapping can easily be done according to `user.user_id`, `user.name`, `user.email`, whereas the `user` represents the response object.

However, a response may look like as given in example # 01 where the user data is stored in the [response].data subobject with a required mapping according to `user.data.user_id`, `user.data.name`, `user.data.email`.

**Comment by clokep** [comment]
Jinja2 should automatically handle that, I think:

```pycon
>>> user = {
    "data": {
        "user_id": "1056",
        "name": "John Doe",
        "email": "email@example.com"
    }
}
>>> import jinja2
>>> template = jinja2.Template("{{ user.data.user_id }}")
>>> template.render(user=user)
'1056'
```

Did you try using a `localpart_template` like you suggested in your first comment: `{{ user.data.id }}`. I *think* it will work, but I'm not 100% sure.

**Comment by menturion** [comment]
Right, I tried to map it like so ...

```
    user_mapping_provider:
      config:
        localpart_template: "{{ user.data.user_id }}"
        display_name_template: "{{ user.data.name }}"
        email_template: "{{ user.data.email }}"
```
which doesn't work for example # 01 of the user info endpoint.

I ended up with the "standard" mapping like...

```
    user_mapping_provider:
      config:
        localpart_template: "{{ user.user_id }}"
        display_name_template: "{{ user.name }}"
        email_template: "{{ user.email }}"
```
and rewriting the Oauth2 user info endpoint, now returning a flat user object like in example # 02.
