### ISSUE TITLE
ldap start_tls doesn't work

### ISSUE THREAD

**Issue by 4nd3r** [matrix-org/synapse#1181]
debian jessie
matrix-synapse 0.18.1-1
python-ldap3 0.9.4.2-1

```
ldap_config:
  enabled: true
  uri: "ldap1.example.com"
  start_tls: false
  base: "ou=users,dc=example,dc=com"
  attributes:
    uid: "uid"
    mail: "mail"
    name: "cn"
```

setting `start_tls: true` and in log:

```
synapse.handlers.auth - 552 - WARNING - POST-8- Error during LDAP authentication: unable to send message, socket is not open
```

adding `ldap://` or `ldaps://` or port in `uri` doesn't have any effect.

setting `start_tls: false` works.

ldap server certificate is "green" and root ca certificates are in ca-certificates.
