### ISSUE TITLE
Each time a new user is created with a number after migration (User1:example.com)

### ISSUE THREAD

**Issue by rtest12** [matrix-org/synapse#12307]
I have the same problem as #9514
I migrated to a new server, no upgrade, just latest version to latest.
Users1-2-3 began to be created
I changed the old value idp_id from 
```
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
   - idp_id: keycloak
     idp_name: "keycloak"
```
For new
```
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
   - idp_id: oidc
     idp_name: "keycloak"
```

I restarted the entire installation, but nothing has changed, still when I log in I get "User1:example.com" 
I don't understand what else I missed?

all conf

```
matrix_synapse_configuration_extension_yaml: |
 oidc_providers:
  - idp_id: oidc
    idp_name: "keycloak"
    issuer: "https://id.exam.com/auth/realms/myrealm"
    client_id: "synapse"
    client_secret: "mykey"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
          email_template: "{% raw %}{{ user.email }}{% endraw %}"


```
Also additionally added
`   allow_existing_users: true`
But it didn't help
