### ISSUE TITLE
The default OIDC handler ignores email scope when creating new users

### ISSUE THREAD

**Issue by tucnak** [matrix-org/synapse#12605]
### Description

I've set up a SSO interface using OIDC (OpenID Connect) and the default mapping provider that goes with it.

I can see quite clearly from the debug logs that it's actually able to retrieve the email scope successfully, but it won't reflect in the client as such.

homeserver.yaml
```yaml
oidc_providers:
  - idp_id: backend
    idp_name: "Hrest.org"
    issuer: "https://api.myweb.site/oauth2"
    client_id: "synapse"
    client_secret: "synapse-secret"
    scopes: ["openid", "profile", "email"]
    user_profile_method: "userinfo_endpoint"
    allow_existing_users: true
    user_mapping_provider:
      config:
        localpart_template: "{{ user.sub }}"
        display_name_template: "{{ user.name }}"
        email_template: "{{ user.email }}"
```

homeserver.log
```
2022-05-02 01:07:47,603 - synapse.handlers.oidc - 882 - DEBUG - GET-10- Userinfo for OIDC login:
{'sub': 'Brody40', 'name': 'Ilya Kowalewski', 'given_name': 'Ilya', 'family_name': 'K', 'preferred_username': 'Brody40', 'email': 'badt@aletheia.icu', 'email_verified': True, 'locale': 'en'}j
2022-05-02 01:07:47,620 - synapse.handlers.sso - 519 - DEBUG - GET-10- Retrieved user attributes from user mapping provider: 
UserAttributes(localpart='brody40', confirm_localpart=False, display_name='Ilya K', emails=['badt@aletheia.icu']) (attempt 0)
```

Even though that seems to be the case, when opening the user profile in Element web, it doesn't show said email as belonging to said user.

### Steps to reproduce

- Set up a OIDC provider with default mapping
- Make an authorisation using client_secret method
- Confirm with logs that the email has been retrieved
- Check for user's email information, it's not been set.

I would expect the user to indeed have the login email set.

### Version information

Our homeserver is running Synapse [v1.57.1](https://hub.docker.com/layers/synapse/matrixdotorg/synapse/v1.57.1/images/sha256-c30ec59505505392ae13e51f6cadf912a8873b12e7fa3765e5fbbefb86ede6a3?context=explore).

- **Version**:

v1.57.1

- **Install method**:

Docker, docker-compose

- **Platform**:

Debian 10
