### ISSUE TITLE
ipv6 appservice url not working

### ISSUE THREAD

**Issue by martinetd** [matrix-org/synapse#13081]
### Description

Trying to set `url: http://[::1]:8010` in one of the `app_service_config_files:` yaml files fails to connect with the following error:

`synapse[3490779]: synapse.appservice.api: [as-recoverer-telegram-5] push_bulk to http://[::1]:8010/transactions/1 threw exception(InvalidCodepoint) Codepoint U+003A at position 1 of '::1' not allowed args=("Codepoint U+003A at position 1 of '::1' not allowed",)`

### Steps to reproduce

- (not sure if actually needed) setup an app service bridge, make it listen on ipv6
- configure synapse to connect to it with its litteral ipv6 and restart synapse
- observe the error (after an user tries to talk to one of the bridge bots?)

relevant part of config, main config:
```
app_service_config_files:
- /var/lib/matrix-synapse/telegram-registration.yaml
```
yaml file:
```
id: telegram
as_token: xxx
hs_token: xxx
namespaces:
    users:
    - exclusive: true
      regex: '@tg_.*:homeserver\.my'
    - exclusive: true
      regex: '@tgbot:homeserver\.my'
    aliases:
    - exclusive: true
      regex: \#tg_.*:homeserver\.my
url: http://localhost:8010
sender_localpart: xxx
rate_limited: false
```

### Homeserver

not relevant

### Synapse Version

{"server_version":"1.60.0","python_version":"3.9.13"}

### Installation Method

Other (please mention below)

### Platform

nixpkgs-unstable, using the standard service

### Relevant log output

```shell
synapse[3490779]: synapse.appservice.api: [as-recoverer-telegram-5]
push_bulk to http://[::1]:8010/transactions/1 threw exception(
   InvalidCodepoint) Codepoint U+003A at position 1 of '::1' not allowed
   args=("Codepoint U+003A at position 1 of '::1' not allowed",)
```

### Anything else that would be useful to know?

a quick search showed that error probably comes from IDNA, but IDNA is not directly called so I have no idea what path it took from `synapse/appservice/api.py` to that error -- if there's a way to display a full stack trace I'd gladly oblige.

Otherwise it should be trivial to reproduce.

Thank you.
