### ISSUE TITLE
If a "Limit Exceeded" error is returned, there should be no change to the database.

### ISSUE THREAD

**Issue by RomanOlegovich** [matrix-org/synapse#13427]
### Description

1. If a "Limit Exceeded" error is returned, there should be no change to the database.

2. I have configs like below, it has a big speed limit. I tried send 3000 request synchronously (one by one). Why I got this error?
```
rc_registration:
 per_second: 1000
 burst_count: 1000

rc_login:
 address:
  per_second: 1000
  burst_count: 1000
 account:
  per_second: 1000
  burst_count: 1000

rc_admin_redaction:
 per_second: 1000
 burst_count: 1000

rc_joins:
 local:
  per_second: 1000
  burst_count: 1000
 remote:
  per_second: 1000
  burst_count: 1000

rc_invites:
 per_room:
  per_second: 1000
  burst_count: 1000
 per_user:
  per_second: 1000
  burst_count: 1000
```

### Steps to reproduce

- Send 3000 requests one by one to create a rooms. In my case it's direct room.
- Get error: "Limit exceeded" + "retry_after_ms=N",
- Wait N ms plus a 5 seconds
- Repeat the request
- Get error: "Room alias already taken"

### Homeserver

homeserver

### Synapse Version

{"server_version":"1.63.1","python_version":"3.9.13"}

### Platform

container in swarm

### Relevant log output

```shell
- Has not, but I'll do this if need
```

**Comment by richvdh** [comment]
Essentially a duplicate of #8895 I think

**Comment by RomanOlegovich** [comment]
@richvdh Why I get rate limit exception if was set as below?
```
rc_invites:
 per_room:
  per_second: 1000
  burst_count: 1000
 per_user:
  per_second: 1000
  burst_count: 1000
```
