### ISSUE TITLE
"Must only specify one instance to handle `to_device` messages" when 0 instances are specified

### ISSUE THREAD

**Issue by spantaleev** [matrix-org/synapse#13804]
### Description

```yaml
stream_writers:
  account_data: []
  events: []
  presence: []
  receipts: []
  to_device: []
  typing:
  - matrix-synapse-worker-background-worker-0-stream_writer-typing
```

The following configuration leads to an error message:

> Must only specify one instance to handle `to_device` messages

Removing `to_device: []` completely helps, but I'd expect that specifying it as an empty list should also work.

I'm building the list programatically, so starting with empty lists and injecting worker names into them was more convenient.

### Steps to reproduce

Add the above configuration to your YAML and restart the worker you have (or the main process, I suppose).

### Homeserver

another homesever

### Synapse Version

v1.67.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

VM/container, irrelevant

### Relevant log output

```shell
Must only specify one instance to handle `to_device` messages
```
