### ISSUE TITLE
Critical error hidden in logging type INFO

### ISSUE THREAD

**Issue by aceArt-GmbH** [matrix-org/synapse#14367]
### Description

I was trying to add an event_persister worker via docker-compose using `synapse_worker_event_persister1` as service name which also is the docker DNS record.
But apparently `_` is not allowed for event_persister host's (which IMO is a bug on its on).

The error was only visible when showing "INFO" logs

### Steps to reproduce

- add a generic worker in docker-compose.yaml with `synapse_worker_event_persister1` as name
- reference it
```yaml
instance_map:
    event_persister1:
        host: synapse_worker_event_persister1
        port: 8034
```

- send requests and get `M_UNKNOWN: Failed to talk to event_persister1 process`
- show docker logs and see nothing 

```yaml
version: 1

formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:


  console:
    class: logging.StreamHandler
    formatter: precise

loggers:
    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO

root:
    level: WARN


    handlers: [console]


disable_existing_loggers: false
```

- change root.level to INFO to finally see error

### Homeserver

self hosted

### Synapse Version

1.70.1

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

linux

### Relevant log output

```shell
2022-11-04 14:19:14,311 - synapse.http.client - 455 - INFO - POST-5 - Error sending request to POST http://synapse_worker_event_persister1:8034/_synapse/replication/send_events/JfZHQlavDY: InvalidCodepoint Codepoint U+005F at position 8 of 'synapse_worker_event_persister1' not allowed
```
