### ISSUE TITLE
Read homeserver.yaml variables from files (e.g. docker secrets) and environment variables.

### ISSUE THREAD

**Issue by RandomExplosion** [matrix-org/synapse#14512]
Hi All, I've been setting up my own homeserver recently and I've come across an issue that many seem to have raised before me;
For the purpose of storing and backing up configuration it is not ideal to have secrets embedded within the config files themselves e.g. private keys, database passwords etc.

**Description:**
I would like to propose that support be added for reading particular config variables (and perhaps any config variable down the track) from a file at an arbitrary path (say by adding -file to the end of any given config file). A similar approach could also be used for environment variable support as well. Similar to how authelia handles the same problem (see [here](https://www.authelia.com/configuration/methods/secrets/))

**Suggested Implementation**
As for how this would be implemented, the easiest (albeit least efficient) approach I can think of would be to check all the attributes in a given config object (using something like `.vars()`) for a suffix such as `"-file"` or `"-env"` suffix (using something like python's string `endswith()` method)
Then whenever a match is found it could just attempt to read the file or environment variable into a new attribute with the suffix removed  the contents of the file or environment variable.

The recursive nature of that approach is definitely slower but i figure since afaik it will only be happening at server startup it shouldn't be that bad as a first implementation. (The search could also be disabled by default as to not affect those who aren't going to use the feature.) 

I'm be more than happy to implement this and make a PR myself. I just want to confirm that such a feature would be accepted.

**Comment by RandomExplosion** [comment]
An example use case - Postgres Connection Password:
### **Current:** 
```yaml
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: synapse
    password: "sensitiveSecretInConfigFile"
    database: synapse
    host: infra-synapse_db-1
    port: 5432
    cp_min: 5
    cp_max: 10
```
### **Proposed:**
#### Suffixed
```yaml
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: synapse
    password_file: "/run/secrets/SYNAPSE_POSTGRES_PASSWORD"
    database: synapse
    host: infra-synapse_db-1
    port_env: "SYNAPSE_POSTGRES_PORT"
    cp_min: 5
    cp_max: 10

```

#### Bash-Like Interpolation Syntax (Proposed by @richvdh:sw1v.org)
```yaml
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: synapse
    password: "${file:/run/secrets/SYNAPSE_POSTGRES_PASSWORD}"
    database: synapse
    host: infra-synapse_db-1
    port: "${SYNAPSE_POSTGRES_PORT}"
    cp_min: 5
    cp_max: 10
```
