### ISSUE TITLE
NotImplementedError: Attempting to check presence on a non-presence worker

### ISSUE THREAD

**Issue by nishant378** [matrix-org/synapse#15057]
**Description**
My workers works fine when i don't mention presence in my main config file (stream_writers), but when i mention presence in stream_writers my status, sync apis doesn't work when i mention presence in stream_writers (for other user). When i remove presence from stream_writers then it works fine. 

I want to use presence worker for better cpu usage. How can i solve this?

**Homeserver**
another homeserver
homeserver.yaml
```
instance_map:
generic_worker1:
        host: [localhost](http://localhost/)
        port: 9094
    generic_worker2:
        host: [localhost](http://localhost/)
        port: 9095
    generic_worker3:
        host: [localhost](http://localhost/)
        port: 9096
    generic_worker4:
        host: [localhost](http://localhost/)
        port: 9097
    additional1:
        host: [localhost](http://localhost/)
        port: 9098
    presence:
        host: [localhost](http://localhost/)
        port: 9100
stream_writers:
  events:
     - generic_worker1
     - generic_worker2
     - generic_worker3
     - generic_worker4
  presence:
     - presence
  account_data:
     - additional1
```

**Synapse Version**
1.65

**Installation Method**
pip (from PyPI)

**Database**
PostgreSQL 12

**Workers**
Multiple workers

presence.yaml
```
worker_app: synapse.app.generic_worker worker_name: presence

The replication listener on

the synapse to talk to.

worker_pid_file: /root/matrix-backend-repo/

worker replication_host: 127.0.0.1 worker_replication_http_port: 9093 riot-matrix/synapse/presence.pid #worker_log_config: /etc/matrix-synapse/workers/ presence_log_config.yaml

worker_listeners:

⚫ type: http

bind_addresses: ['127.0.0.1'] port: 8516

tls: false

x_forwarded: true

resources:

O names: [client] compress: false

⚫ type: http bind_addresses: ['127.0.0.1']

port: 9100 resources:

O names: [replication]

type: metrics

bind_addresses: ['0.0.0.0'] port: 9137
```
Reverse proxy for presence in nginx

```
location/_matrix/client/(api/v1|r0|v3|unstable)/

presence/ {

include conf.d/synapse-proxy.conf;

proxy_pass http://presence; }
```

**Platform**
Ubuntu 18.04
VM

**Configuration**
Presence: true

**Relevant log output**
```
Traceback (most recent call last):

File "/root/matrix-backend-repo/riot-matrix/ synapse/synapse/http/server.py", line 368, in _async_render_wrapper callback_return = await self._async_render(request) File "/root/matrix-backend-repo/riot-matrix/

synapse/synapse/http/server.py", line 574, in

_async_render callback_return = await raw_callback_return

File "/root/matrix-backend-repo/riot-matrix/

synapse/synapse/rest/client/presence.py", line 56, in

on_GET

allowed = await self.presence_handler.is_visible( File "/root/matrix-backend-repo/riot-matrix/ synapse/synapse/handlers/presence.py", line 368, in is_visible

raise NotImplementedError(

NotImplementedError: Attempting to check presence on a non-presence worker.

```
