### ISSUE TITLE
email not working

### ISSUE THREAD

**Issue by nephilim75** [matrix-org/synapse#15119]
### Description

I try to receive mails from matrix server but it won't working.

### Steps to reproduce

- added smtp configuration to homeserver.yaml as described [here](https://github.com/devture/email2matrix/blob/master/etc/services/matrix-synapse/homeserver.yaml)

```
email:
   enable_notifs: false
   smtp_host: mail.domain.com
   smtp_port: 465
   smtp_user: "matrix@domain.com"       #tried with " and without
   smtp_pass: "secret_password"         #tried with " and without
   require_transport_security: true
   notif_from: "Your Friendly %(app)s Home Server <noreply@example.com>"
   app_name: Matrix
```

Then I tried to add a mail address to one of my users. `Element` tells me that it will send a mail for verification but this one never arrives. I doublecked inbox and spam.

I have re-created the smtp mailbox more than once an double-checked spelling of each entry. It is correct at any time.

No idea wher to seach and find a solution.

Any help appreciated.

### Homeserver

matrix.domain.com

### Synapse Version

{"server_version":"1.77.0","python_version":"3.10.6"}

### Installation Method

Other (please mention below)

### Database

Postgres

### Workers

Single process

### Platform

Ubuntu 22.04

### Configuration

.

### Relevant log output

```shell
.
```
