### ISSUE TITLE
Element Redirect to Matrix url instead of element address after signing with google

### ISSUE THREAD

**Issue by click23** [matrix-org/synapse#15117]
Steps to reproduce
I'm use 2 separate servers, one for element and one for matrix with reverse proxy. after adding the id and key of google cloud into homeserver.yaml "google sign in" appeared on the personal element web page.

Outcome
What did you expect?
After signing in Google asks for credentials and redirects to element web server for logging into matrix server.

What happened instead?
But after clicking on the Google signing in I receive some issue about the redirect url which points to matrix server instead of the element server.

Sure ...
To be more complete on server A Matrix is installed plus caddy reverse proxy and turn server so turn.domain.com and mat.domain.com are on server A and Element is installed on server B so element.domain.com points to server B.

 
Here is the Matrix Configuration

```
pid_file: "/var/run/matrix-synapse.pid"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: synapse_user
    password: ***
    database: synapse
    host: localhost
    cp_min: 5
    cp_max: 10
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"
registration_shared_secret: ***

turn_uris: [ "turn:turn.domain.com?transport=udp", "turn:turn.domain.com?transport=tcp" ]
turn_shared_secret: "mysecretkey"
turn_user_lifetime: 86400000
turn_allow_guests: true

oidc_providers:
  - idp_id: google
    idp_name: Google
    idp_brand: "google"  # optional: styling hint for clients
    issuer: "https://accounts.google.com/"
    client_id: "*******************************************************" # TO BE FILLED
    client_secret: "**********************************************************" # TO BE FILLED
    scopes: ["profile", "email"] # email is optional, read below
    user_mapping_provider:
      config:
        localpart_template: "{{ user.given_name|lower }}"
        display_name_template: "{{ user.name }}"
        email_template: "{{ user.email }}" # needs "email" in scopes above

```
Here is the Element conf.json

```                                                                          
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://mat.domain.com",
            "server_name": "mat.domain.com"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "disable_custom_urls": false,
    "disable_guests": false,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "Element",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "uisi_autorageshake_app": "element-auto-uisi",
    "default_country_code": "GB",
    "show_labs_settings": false,
    "features": {},
    "default_federate": true,
    "default_theme": "light",
    "room_directory": {
        "servers": ["matrix.org"]
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "setting_defaults": {
        "breadcrumbs": true
    },
    "jitsi": {
        "preferred_domain": "meet.element.io"
    },
    "element_call": {
        "url": "https://call.element.io",
        "participant_limit": 8,
        "brand": "Element Call"
    },
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}
```
