### ISSUE TITLE
OIDC: Synapse crashes if provider is unavailable at startup

### ISSUE THREAD

**Issue by acuteaura** [matrix-org/synapse#15505]
### Description

When using an OIDC provider as a secondary login method, Synapse will crash if the provider is unavailable at startup.

This is rather unfortunate if you are running an IdP alongside Synapse, let's say in a composefile. It required me to build keycloak with a `curl` binary inside the container and implement health checks.

### Steps to reproduce

- configure OIDC IdP
- make sure it's unavailable
- start synapse

### Homeserver

N/A

### Synapse Version

1.81.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

N/A

### Workers

Single process

### Platform

N/A

### Configuration

```
oidc_providers:
  - idp_id: keycloak
    idp_name: "<snip>"
    issuer: "https://<snip/realms/<snip>"
    client_id: "synapse"
    client_secret: "<snip>"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.name }}"
    backchannel_logout_enabled: true
```

### Relevant log output

```shell
N/A
```
