### ISSUE TITLE
OIDC Redirect error when using a subdomain

### ISSUE THREAD

**Issue by mpldr** [matrix-org/synapse#15540]
### Description

I want to attach my SSO server (running authentik) to my synapse instance, which has been easy enough. Now my server is running on a subdomain (matrix.) and the redirect does not take this into account:

```console
$ curl -IL 'https://matrix.poldrack.dev/_matrix/client/r0/login/sso/redirect/oidc-authentik?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F&org.matrix.msc3824.action=login' 
HTTP/2 302 
alt-svc: h3=":443"; ma=2592000
content-type: text/html
date: Fri, 05 May 2023 06:40:03 GMT
location: https://poldrack.dev/_matrix/client/r0/login/sso/redirect/oidc-authentik?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F&org.matrix.msc3824.action=login
server: Caddy
server: Synapse/1.82.0

HTTP/2 308 
access-control-allow-methods: HEAD,GET
access-control-allow-origin: *
access-control-max-age: 86400
alt-svc: h3=":443"; ma=2592000
content-type: application/json
date: Fri, 05 May 2023 06:40:18 GMT
location: https://matrix.poldrack.dev/_matrix/client/r0/login/sso/redirect/oidc-authentik?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F&org.matrix.msc3824.action=login
permissions-policy: interest-cohort=()
referrer-policy: no-referrer-when-downgrade
server: Caddy
server: Caddy
x-content-type-options: nosniff
x-frame-options: DENY

HTTP/2 302 
alt-svc: h3=":443"; ma=2592000
content-type: text/html
date: Fri, 05 May 2023 06:40:18 GMT
location: https://poldrack.dev/_matrix/client/r0/login/sso/redirect/oidc-authentik?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F&org.matrix.msc3824.action=login
server: Caddy
server: Synapse/1.82.0

HTTP/2 308 
access-control-allow-methods: HEAD,GET
access-control-allow-origin: *
access-control-max-age: 86400
alt-svc: h3=":443"; ma=2592000
content-type: application/json
date: Fri, 05 May 2023 06:40:18 GMT
location: https://matrix.poldrack.dev/_matrix/client/r0/login/sso/redirect/oidc-authentik?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F&org.matrix.msc3824.action=login
permissions-policy: interest-cohort=()
referrer-policy: no-referrer-when-downgrade
server: Caddy
server: Caddy
x-content-type-options: nosniff
x-frame-options: DENY
```

### Steps to reproduce

- see above

### Homeserver

matrix.poldrack.dev

### Synapse Version

{"server_version":"1.82.0","python_version":"3.11.3"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

postgres

### Workers

Single process

### Platform

```console
$ uname -a
Linux helios.moritz.sh 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               AuthenticAMD
  Model name:            QEMU Virtual CPU version 2.5+
    CPU family:          6
    Model:               13
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            3
    BogoMIPS:            3994.85
    Flags:               fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx
                          fxsr sse sse2 ht syscall nx lm nopl cpuid tsc_known_freq pni pclmulqdq ssse3 c
                         x16 sse4_1 sse4_2 x2apic popcnt aes xsave rdrand hypervisor lahf_lm cmp_legacy 
                         abm 3dnowprefetch ssbd ibpb vmmcall arch_capabilities
```

### Configuration

```yml
oidc_providers:
  - idp_id: authentik
    idp_name: ID Server
    discover: true
    issuer: "https://id.moritz.sh/application/o/matrix/"
    client_id: "DYksKcflYQK3TuCiFD5MaLlhWyMf3TZl9xw54HPx"
    client_secret: "redacted"
    scopes:
      - "openid"
      - "profile"
      - "email"
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.preferred_username|capitalize }}"
```

### Relevant log output

```shell
not applicable
```
