### ISSUE TITLE
SSO login via CAS create user with registration disabled

### ISSUE THREAD

**Issue by agrimpard** [matrix-org/synapse#15775]
### Description

If a user logs in with SSO (CAS) but is not registered in Matrix's user database, he should get an error warning that he is not authorized to access the service (401).

However, Matrix will automatically register the user regardless of the registration disabled parameter, then let him connect to the server and use the service.

### Steps to reproduce

Matrix config homeserver.yaml :

```
enable_registration: false
cas_config:
  enabled: true
  server_url: "https://cas.mydomain.com"
```

### Homeserver

Private server

### Synapse Version

1.85.0

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL

### Workers

Single process

### Platform

KVM / Debian 11

### Relevant log output

```shell
Not relevant ?
```
