### ISSUE TITLE
Multiple uploads resulting in CANCELED

### ISSUE THREAD

**Issue by Cyberes** [matrix-org/synapse#15841]
### Description

I am attempting to upload two video files (each about 30 MB) to a room at the same time. This always fails with a generic error message popup (`The file '[filename]' failed to upload.`). There is no error in the console and the network of the debug window shows the fetch request as `(canceled)`. Synapse logs don't show any errors and neither does Openresty. Uploading the files one at a time works, but uploading them together always fails.

My upload limit in Synapse and Openresty is 40M. This has been an issue for a while and I have not discovered the root cause yet.
My client is desktop and web Element on Ubuntu.

### Steps to reproduce

- ???

### Homeserver

matrix.evulid.cc

### Synapse Version

1.86.0

### Installation Method

pip (from PyPI)

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

Ubuntu Server LXC container

### Relevant log output

```shell
No unusual logs.
```

**Comment by Cyberes** [comment]
Looks like the 30MB file fails when individually uploaded.

**Comment by MadLittleMods** [comment]
I know you mentioned that there aren't any relevant logs but seems like it could be related to https://github.com/matrix-org/synapse/issues/12937 -> https://github.com/matrix-org/synapse/issues/13009

Are you using Element to upload the file? Element will cancel the request if it doesn't see any progress for 30 seconds (see [`matrix-org/matrix-js-sdk` -> `src/http-api/index.ts#L102-L111`](https://github.com/matrix-org/matrix-js-sdk/blob/acbcb4658a5d5903dfd557e3e115241d0a6f38bb/src/http-api/index.ts#L102-L111))

It seems like TCP dumps from the client <-> server would be useful to debug this further.

Other related issues:

 - https://github.com/matrix-org/synapse/issues/6192
 - https://github.com/matrix-org/synapse/issues/11154#issuecomment-948876317

**Comment by Cyberes** [comment]
I'm no web developer, but I checked the debugger and saw that I am indeed triggering the timeout. The upload only takes a few seconds but the bar sits at 100% for a bit before the timeout kills it.

**Comment by clokep** [comment]
Is your reverse proxy killing the upload? I think by default they usually have small limits.

**Comment by MadLittleMods** [comment]
@Cyberes Does the media end up on your server after the dust settles? (if so, feels like it's one of the issues I've already linked)

@clokep also has an interesting angle with the reverse-proxy.

Otherwise, seems like a case of tracing or adding logs to see where Synapse is stuck at. I've added some extra instrumentation so traces provide a lot more info when using the `/upload` endpoint -> https://github.com/matrix-org/synapse/pull/15850

Are you able to [enable tracing](https://matrix-org.github.io/synapse/latest/opentracing.html) for your Synapse instance (will need wait for the PR to merge or apply those changes manually)?

**Comment by Cyberes** [comment]
There isn't anything in the nginx error logs. I have `client_max_body_size 40M;` in my config.

And `find /mnt/matrix-storage/ -iname "[ID returned by /upload]"` doesn't return anything.

I'll pull that branch and enable tracing.

**Comment by Cyberes** [comment]
Sent the trace JSON in a DM.

**Comment by MadLittleMods** [comment]
Thanks for trace @Cyberes!

It doesn't appear to be a bug in Synapse given that the file ends up on your server and the trace shows that it's working but just has a long period where it blocks while storing the file (probably the `shutil.copyfile` part). It's probably just Synapse or your system being slow to store the file and Element doesn't gracefully handle that case.

What does your `homeserver.yaml` look like (`media_store_path`, `media_storage_providers`)?

I've also made the tracing less ambiguous since there are so many shared names that make my head hurt trying to correlate to the code, https://github.com/matrix-org/synapse/pull/15888. Also added an extra trace around the `shutil.copyfile` part specifically to see if it's that. Post another trace when you get a chance to run with that code :crossed_fingers:

**Comment by Cyberes** [comment]
```yaml
media_store_path:                                 "/mnt/matrix-storage/media"

media_storage_providers:
- module:                                         s3_storage_provider.S3StorageProviderBackend
  store_local:                                    True
  store_remote:                                   True
  store_synchronous:                              True
  config:
      bucket:                                     matrix-synapse
      endpoint_url:                               'https://xxx.r2.cloudflarestorage.com/matrix-synapse'
      access_key_id:                              'xxx'
      secret_access_key:                          'xxx'
```

Ah, I forgot about S3! It might be slow to send it to S3.

[evulid.cc media_worker UploadResource less ambiguous.json.txt](https://github.com/matrix-org/synapse/files/11972871/evulid.cc.media_worker.UploadResource.less.ambiguous.json.txt)
