### ISSUE TITLE
Since 1.86, the "login via QR code" feature does not work even if `matrix-http-rendezvous-synapse` is installed.

### ISSUE THREAD

**Issue by YamatoRyou** [matrix-org/synapse#15918]
### Description

I recently upgraded Synapse to 1.86 (and then to 1.87), but then found that the "Login via QR code" feature disappeared in the client (Element Desktop & Web).
Version number <= 1.85 is back to normal. I can't tell whether the fault is Synapse or `matrix-http-rendezvous-synapse`.

According to the usage given by `https://pypi.org/project/matrix-http-rendezvous-synapse/`, visit `https://<myserver.com>/_synapse/client/org.matrix.msc3886/rendezvous` Return `HTTP 405` error.

----
If this article is not related to Synapse, please mark it as closed.

### Steps to reproduce

n/a

### Homeserver

Self-hosted

### Synapse Version

Synapse 1.87.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL 14.5

### Workers

Single process

### Platform

Synology DiskStation Manager 6.2.3 (Linux 3.10.105 x86_64)

### Configuration

GET `/_matrix/client/versions`
```
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0","r0.6.1","v1.1","v1.2","v1.3","v1.4","v1.5","v1.6"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666.query_mutual_rooms":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false,"org.matrix.msc3026.busy_presence":false,"org.matrix.msc2285.stable":true,"org.matrix.msc3827.stable":true,"org.matrix.msc3440.stable":true,"org.matrix.msc3771":true,"org.matrix.msc3773":false,"fi.mau.msc2815":false,"fi.mau.msc2659.stable":true,"org.matrix.msc3882":false,"org.matrix.msc3881":false,"org.matrix.msc3874":false,"org.matrix.msc3886":true,"org.matrix.msc3912":false,"org.matrix.msc3981":false,"org.matrix.msc3391":false}}
```

----
homeserver.yaml
```
modules:
  - module: matrix_http_rendezvous_synapse.SynapseRendezvousModule
    config:
      prefix: /_synapse/client/org.matrix.msc3886/rendezvous
```
```
experimental_features:
  msc3882_enabled: true
  msc3882_ui_auth: false
  msc3886_enabled: true
  msc3886_endpoint: /_synapse/client/org.matrix.msc3886/rendezvous
```

### Relevant log output

n/a

### Anything else that would be useful to know?

Since the installation of `matrix-http-rendezvous-synapse` did not fail, and access to `http://<myserver.com>/_synapse/client/org.matrix.msc3886/rendezvous` did not give any description of the error log.

**Comment by hughns** [comment]
MSC3882 was approved and accepted into v1.7 of the Matrix spec.

v1.86 of Synapse added support for this new stable feature and removed support for the experimental feature.

These options are no longer valid:
```
  msc3882_enabled: true
  msc3882_ui_auth: false
```

The new stable options are detailed here:
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#login_via_existing_session

**Comment by YamatoRyou** [comment]
> [MSC3882](https://github.com/matrix-org/matrix-spec-proposals/pull/3882) was approved and accepted into v1.7 of the Matrix spec.
> 
> v1.86 of Synapse added support for this new stable feature and removed support for the experimental feature.
> 
> These options are no longer valid:
> 
> ```
>   msc3882_enabled: true
>   msc3882_ui_auth: false
> ```
> 
> The new stable options are detailed here: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#login_via_existing_session

The sorted out solution is:
1. `matrix-http-rendezvous-synapse` still needs to be installed.
2. Edit `homeserver.yaml`:  
Add the following content:  

```  
login_via_existing_session:
   enabled: true
   require_ui_auth: false
   token_timeout: "5m"
```  

Delete the following (MSC3882 has become a stable feature, so removed from `experimental_features`):
From:

```  
experimental_features:
    msc3882_enabled: true
    msc3882_ui_auth: false
    msc3886_enabled: true
    msc3886_endpoint: /_synapse/client/org.matrix.msc3886/rendezvous
```
To:
```
experimental_features:
    msc3886_enabled: true
    msc3886_endpoint: /_synapse/client/org.matrix.msc3886/rendezvous
```

The following remain as they are:
```
modules:
   - module: matrix_http_rendezvous_synapse.SynapseRendezvousModule
     config:
       prefix: /_synapse/client/org.matrix.msc3886/rendezvous
```

3. Restart Synapse.
