### ISSUE TITLE
Use LDAP dn from search results for user authentication

### ISSUE THREAD

**Issue by mirrom** [matrix-org/synapse#1637]
We are using a Microsoft Active Directory LDAP where an entry for a user looks like this:

`dn: cn=Firstname Lastname,ou=OrganizationUnit,dc=example,dc=com`

Additionally we use the field:

`sAMAccountName: lastname`

We use `sAMAccountName` as `uid` as a matrix synapse account name does not allow a space. So our configuration looks like this:

```yaml
ldap_config:
      enabled: true
      uri: "ldap://example.com:389"
      start_tls: false
      base: "ou=OrganizationUnit,dc=example,dc=com"
      attributes:
        uid: "sAMAccountName"
        mail: "mail"
        name: "cn"
      bind_dn: "ldap"
      bind_password: "password"
      filter: "(objectCategory=Person)"
```

The authentication with the user given in `bind_dn` and `bind_password` in the LDAP configuration works fine:

```
synapse.util.ldap_auth_provider - 294 - DEBUG - POST-0- Established LDAP connection in search mode: ldap://example.com:389 - cleartext - user: ldap - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
```

Also the search filter and the search results work:

```
synapse.util.ldap_auth_provider - 325 - DEBUG - POST-0- LDAP search filter: (&(sAMAccountName=lastname)(objectCategory=Person))
synapse.util.ldap_auth_provider - 335 - DEBUG - POST-0- LDAP search found dn: CN=Firstname Lastname,OU=OrganizationUnit,DC=example,DC=com
```

But binding against LDAP fails for the given user:

```
synapse.util.ldap_auth_provider - 261 - INFO - POST-0- Binding against LDAP failed for 'lastname' failed: invalidCredentials
```

The authentication against our LDAP only works with `dn`, not with `sAMAccountName`. Taken from the debug output and form `ldap_auth_provider.py` it looks like it tries to bind the user with the field given in `uid`:

```python
    def _ldap_simple_bind(self, server, localpart, password):
        try:
            bind_dn = "{prop}={value},{base}".format(
                prop=self.ldap_attributes['uid'],
                value=localpart,
                base=self.ldap_base
```

This doesn't work for us, this results in `sAMAccountName=lastname,ou=OrganizationUnit,dc=example,dc=com` which is not a valid `dn`. Is it possible to change the complete `bind_dn` for the user authentication to the `dn` of the search result? At least optionally?
