### ISSUE TITLE
Installing Synapse on Ubuntu 22.04

### ISSUE THREAD

**Issue by qeeboqeebo** [matrix-org/synapse#16607]
Hello,

I am attempting to follow the instructions for installing Synapse on Ubuntu 22.04 as described here: [https://www.howtoforge.com/how-to-install-matrix-synapse-chat-on-ubuntu-22-04/#install-matrix-synapse-on-ubuntu-](url)

I am up to the section "Configure Matrix Synapse"

The instructions state , after I enter the command nano /etc/matrix-synapse/homeserver.yaml , I should see the text:

```
bind_addresses: ['127.0.0.1']
    enable_registration: false
    registration_shared_secret: "R3jvgiDYyhh5XgduDPsgtwxPDiar8q2s"

However, I only see:

pid_file: "/var/run/matrix-synapse.pid"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /var/lib/matrix-synapse/homeserver.db
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"
```

As such, I do not see any way to "Define your bind-address, disable registration and define your secretes" as the instructions state.

I also do not know how to save and close the yaml file, as I do not see any options for doing so.

Any advice is greatly appreciated.
