### ISSUE TITLE
ldap configuration in homeserver.yaml is outdated

### ISSUE THREAD

**Issue by superboum** [matrix-org/synapse#1693]
When we install matrix-synapse from the debian repository, we have the following part in the file `homeserver.yaml` (commented by default) : 

```yaml
ldap_config:
   enabled: true
   server: "ldap://localhost"
   port: 389
   tls: false
   search_base: "ou=Users,dc=example,dc=com"
   search_property: "cn"
   email_property: "email"
   full_name_property: "givenName"
```

If I try to launch my server with this configuration (and the correct value for each keys !), I've the following error : 

```
LDAP enabled but missing required config values: uri, base, attributes
```

Indeed, lot of modifications were made, and now this configuration file is deprecated and prevent matrix-synapse from booting. I'm currently using the following configuration keys : 

```yaml
ldap_config:
  enabled: true
  uri: "ldap://localhost"
  port: 389
  tls: false
  bind_dn: "dn=Auth,dc=example,dc=com"
  bind_password: "password"
  base: "ou=Users,dc=example,dc=com"
  attributes:
    uid: "cn"
    name: "displayName"
    mail: "mail"
```

*server became uri, search_base became base, search_property, email_property and full_name_property were renamed and placed under attributes*

And my server if now working even if name and mail attributes are not really used yet.
I don't know where and/or how `homeserver.yaml` is generated.
