### ISSUE TITLE
Web client running even when disabled in config

### ISSUE THREAD

**Issue by jrick** [matrix-org/synapse#1883]
I'm running 0.19.0 built from source on centos, and was previously running a synapse 0.18.7 instance on a debian server using the official packages.  I'm not sure if this is related to a change between the package and the source install, or if it is a bug in the 0.19 release.  Regardless, in my config i have the line:

```
web_client: False
```

Yet the bundled web client is still running.

On my previous 0.18 instance, trying to access the server in a web browser opened a 404 error page with the message "No such resource".

**Comment by schnuffle** [comment]
The listener config  contains a resource section:

```
- port: 8008
    tls: false
    bind_address: ''
    type: http

    x_forwarded: false

    resources:
      - names: [client, webclient]
        compress: true
      - names: [federation]
        compress: false
```

Drop the webclient from the resource section of the listeners, where you don't want it to be active.
