### ISSUE TITLE
Log config leads to FD leaks

### ISSUE THREAD

**Issue by schnuffle** [matrix-org/synapse#1908]
In #1858 i started chasing my leaks, which ended in realizing that I'm on the wrong path. So I went back to my first idea, having the feeling that the logging is the culprit, supported  by #1884 which also is a problem with log config.

I wanted to delegate log file writing and rotating to systemd/rsyslog, so I dropped the file handler totally.  	Unfortunately the goal of making it simpler introduced a problem, synapse starts leaking FDs, somtimes straight after a restart, sometimes after some hours.

It's a bit sad, that the part meant to help you seeing problems is the problems cause :).

Affected versions:
- 0.18.7
- 0.19.0
- 0.19.1

I finally have two log configs, one leaking, one doing fine:

# Log config doing fine:
```
version: 1

formatters:
  precise:
   format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s- %(message)s'

filters:
  context:
    (): synapse.util.logcontext.LoggingContextFilter
    request: ""

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: /var/log/synapse/schnuffle.log
    maxBytes: 104857600
    backupCount: 10
    filters: [context]
    level: DEBUG

loggers:
    synapse:
        level: DEBUG

    synapse.storage.SQL:
        level: WARNING

root:
    level: DEBUG
    handlers: [file]
```

# Log config leaking FDs
```

version: 1

formatters:
  precise:
   format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s- %(message)s'

filters:
  context:
    (): synapse.util.logcontext.LoggingContextFilter
    request: ""

handlers:
  console:
    class: logging.StreamHandler
    formatter: precise
    filters: [context]

loggers:
    synapse:
        level: INFO

    synapse.storage.SQL:
        level: ERROR

root:
    level: INFO
    handlers: [console]
```
