### ISSUE TITLE
TemplateNotFound: notif_mail.html in Matrix Synapse homeserver on Ubuntu 16.04

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2331]
I try to configure email notifications in Matrix Synapse homeserver on Ubuntu 16.04.
Here is my config part:
```
public_baseurl: https://chat.mydomain.com/

# Enable sending emails for notification events
email:
   enable_notifs: true
   smtp_host: "localhost"
   smtp_port: 25
        #   smtp_user: "exampleusername"
        #   smtp_pass: "examplepassword"
   notif_from: "Matrix notify <admin+chat@mydomain.com>"
   app_name: Matrix
   template_dir: res/templates
#   notif_template_html: notif_mail.html
   notif_template_html: notif_mail2.html
#   notif_template_html: /etc/matrix-synapse/notif_mail2.html
#   notif_template_text: notif_mail.txt
   notif_template_text: notif_mail2.txt
#   notif_template_text: /etc/matrix-synapse/notif_mail2.txt
   notif_for_new_users: True
   riot_base_url: "https://chat.mydomain.com/"
```

And after trying enable notifications in some user, I see in logs:
```
июл 04 17:33:10 tad python[7902]: 2017-07-04 17:33:10,958 - synapse.http.server - 139 - ERROR - POST-34- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f46a2210b50>: <SynapseRequest at 0x7f46a149c1b8 method=POST uri=/_matrix/client/r0/pushers/set?access_token=<redacted> clientproto=HTTP/1.0 site=8008>
июл 04 17:33:10 tad python[7902]: Traceback (most recent call last):
июл 04 17:33:10 tad python[7902]:   File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
июл 04 17:33:10 tad python[7902]:     yield request_handler(self, request, request_metrics)
июл 04 17:33:10 tad python[7902]: TemplateNotFound: notif_mail2.html
```

How I can debug in which path Synapse really try to find this file?
