### ISSUE TITLE
Error loading config with `ldap_config: enabled: True`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#2912]
A bug introduced in 0.25.0 by ffc574a6 meant that synapse would fail to start if you had the following config in your homeserver.yaml:

```
ldap_config:
    enabled: true
```

The error was:

```
File "/usr/lib/python2.7/dist-packages/synapse/config/password_auth_providers.py", line 34, in read_config
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
```

**Comment by richvdh** [comment]
This has been fixed on [develop](https://github.com/matrix-org/synapse/tree/develop) by 6f05de0 in #2683. Sadly this has not yet been released.

`ldap_config` is now deprecated anyway; users of 0.26.0 can work around this by replacing

 ```
ldap_config:
   # ...
```

with:

```
password_providers:
  - module: "synapse.util.ldap_auth_provider.LdapAuthProvider"
    config:
      # ...
```
