### ISSUE TITLE
Generating log file config doesn't properly indent filename

### ISSUE THREAD

**Issue by mvgorcum** [matrix-org/synapse#3065]
### Description

Generate doesn't produce a proper homserver.log.config

### Steps to reproduce
After running: 
```
python -m synapse.app.homeserver \
               --config-path "${filepath}" \
               --generate-config \
               --report-stats ${REPORT_STATS} \
               --server-name ${SERVER_NAME}
```
It genenrates servername.log.config that looks like:
```
handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
    filename: /data/homeserver.log
        maxBytes: 52428800
        backupCount: 10
        filters: [context]
    console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]
```
But `    filename: /data/homeserver.log`  

Should be indented further to be on the same level as `formatter:` and `maxBytes`
### Version information

- **Homeserver**: Another homeserver

If not matrix.org:
- **Version**:       0.27.2
- **Install method**: Docker (from [silvio/aventer](https://github.com/silvio/docker-matrix))
