### ISSUE TITLE
Synapse is filling my systemd journal, while still keeping its own logs anyway

### ISSUE THREAD

**Issue by ArchangeGabriel** [matrix-org/synapse#3171]
I’m running Synapse 0.27.4 on ArchLinux.

Most of my journalctl ouptut is made of synapse entries. But I also have those logs under `/var/lib/synapse/homeserver.log{,.[0-9]+}`, and honestly I don’t need such a verbose output in my journald.

I’ve tried to find documentation on how to tweak logging, but failed to found any. I’ve found the following in my `homeserver.yaml`:
```
log_config: "/etc/synapse/<domain>.log.config"
```
This files contains:
```
version: 1

formatters:
  precise:
   format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s- %(message)s'

filters:
  context:
    (): synapse.util.logcontext.LoggingContextFilter
    request: ""

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: /var/lib/synapse/homeserver.log
    maxBytes: 104857600
    backupCount: 10
    filters: [context]
    level: INFO
  console:
    class: logging.StreamHandler
    formatter: precise
    filters: [context]

loggers:
    synapse:
        level: INFO

    synapse.storage.SQL:
        level: INFO

root:
    level: INFO
    handlers: [file, console]
```
But I also have a `/etc/synapse/log_config.yaml` file with:
```
version: 1

# In systemd's journal, loglevel is implicitly stored, so let's omit it
# from the message text.
formatters:
    journal_fmt:
        format: '%(name)s: [%(request)s] %(message)s'

filters:
    context:
        (): synapse.util.logcontext.LoggingContextFilter
        request: ""

handlers:
    journal:
        class: systemd.journal.JournalHandler
        formatter: journal_fmt
        filters: [context]
        SYSLOG_IDENTIFIER: synapse

root:
    level: INFO
    handlers: [journal]

disable_existing_loggers: False
```

So what should I modify for synapse to not log everything to journald?

Thanks!
