### ISSUE TITLE
event_sender worker cannot accept federated invite ("No known servers")

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3333]
### Description

When trying to accept an invite, the worker instead instantly returns with a "No Known Servers" error. If I instead redirect the join to the main synapse process it goes through.

The setup is Synapse 0.29.0 with a sync and event sender worker.

Config for the worker is:
```
worker_app: synapse.app.event_creator
server_name: half-shot.uk
report_stats: False

# The replication listener on the synapse to talk to.
worker_replication_host: 127.0.0.1
worker_replication_port: 9592
worker_replication_http_port: 9593

worker_listeners:
 - type: http
   port: 8020
   resources:
     - names:
       - client

worker_daemonize: False
worker_pid_file: /var/run/synapse/event_creator.pid
worker_log_config: /etc/matrix-synapse/workers.conf.d/event_creator.log.cfg
```
