### ISSUE TITLE
Originating request ID has gone missing from log lines

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3588]
There used to be a request ID that could be associated with the outbound request in this:
```
homeserver - 2018-07-23 20:35:30,080 - synapse.http.outbound - 164 - INFO - {GET-O-5511} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/event/%24redacted%3Amatrix.org/
```

**Comment by turt2live** [comment]
https://github.com/matrix-org/synapse/pull/3556 may fix this - to be verified.

**Comment by richvdh** [comment]
hrm, that suggests that something somewhere has leaked a logcontext. If you can share more logs from before the problem, we might be able to figure out where.

**Comment by richvdh** [comment]
> ```
> homeserver_1 - 2018-09-07 19:46:39,742 - synapse.access.https.8558 - 215 - INFO - REDACTED - 8558 - Received request: PUT /_matrix/federation/v1/send/1536162311776/
> ```

This doesn't look right: the fact there is no request ID here (on the very first line when the request arrives) suggests that there's something up with the logging config. Can you share the log config?

**Comment by turt2live** [comment]
It's fairly default:
```
version: 1

formatters:
  precise:
   format: 'homeserver_1 - %(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(message)s'

filters:
  context:
    (): synapse.util.logcontext.LoggingContextFilter
    request: ""

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: /var/log/synapse/homeserver_1.log
    maxBytes: 104857600
    backupCount: 20
    filters: [context]
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: precise
    filters: [context]

loggers:
    synapse:
        level: INFO

    synapse.storage.SQL:
        level: INFO

root:
    level: INFO
    handlers: [file, console]
```
