### ISSUE TITLE
How do I declare Application service?

### ISSUE THREAD

**Issue by oliverjanik** [matrix-org/synapse#3770]
From here: https://matrix.org/docs/spec/application_service/unstable.html#id3

"application services now have to register via configuration files which are linked to the homeserver configuration file"

How do I link configuration files? Where do I put it?  It's great that you have an example:
```
id: "IRC Bridge"
url: "http://127.0.0.1:1234"
as_token: "30c05ae90a248a4188e620216fa72e349803310ec83e2a77b34fe90be6081f46"
hs_token: "312df522183efd404ec1cd22d2ffa4bbc76a8c1ccf541dd692eef281356bb74e"
sender_localpart: "_irc_bot" # Will result in @_irc_bot:domain.com
namespaces:
  users:
    - exclusive: true
      regex: "@_irc_bridge_.*"
  aliases:
    - exclusive: false
      regex: "#_irc_bridge_.*"
  rooms: []
```

But where does this go?

I know this is a community effort but I find the documentation style of this project mildly infuriating. I feel like if I read the source code the documentation will start making sense. :-/
