### ISSUE TITLE
Incomplete doc: postgres

### ISSUE THREAD

**Issue by Extarys** [matrix-org/synapse#4293]
The link for postgresql setup here: https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst

- Bought a new VPS with cent os 7
- Installed postgresql 11
- Installed synapes
- Followed the tutorial, but I chose matrix_synapse as a user instead

I get `2018-12-13 08:42:01,083 - twisted - 244 - ERROR -  - psycopg2.OperationalError: FATAL:  Ident authentication failed for user "matrix_synapse"`

Configuration:
```
database:
    name: psycopg2
    args:
	user: matrix_synapse
        password: engulf5-2tapir-smithy1-5apex-tioga-olaf5-Vet2-scrim-jut-sheath
        database: matrix_synapse
        host: localhost
        cp_min: 5
        cp_max: 10
```

After following the tutorial, it should work.

**Comment by aaronraimist** [comment]
but when you created the database you called the owner of the database `matrix_synapse`? 

In Postgres you can use `\l` to see your databases and the owner. In this example my user is `postgres`.

![screen shot 2018-12-13 at 10 33 21 am](https://user-images.githubusercontent.com/5855073/49952889-84355b80-fec2-11e8-810e-5b9b969e5a33.png)

**Comment by Extarys** [comment]
following the tutorial, the database belong to the user of the same name.
![image](https://user-images.githubusercontent.com/11581433/49977844-dc497d80-ff15-11e8-9011-82dd7e47a67f.png)

**Comment by aaronraimist** [comment]
And you are sure that is the correct password? I know you had posted it here and in `#synapse:matrix.org` so maybe you changed it again?

**Comment by aaronraimist** [comment]
In that command you called your user `synapse_user` not `matrix_synapse`

**Comment by Extarys** [comment]
I triple checked it, I did change the "public" password I gave publicly though to a similar format. I'm actually flushing the server right now to try the docker image and reinstall everything (and write a little document for later use)

**Comment by richvdh** [comment]
Any updates on this? As @aaronraimist says, this sounds like a configuration error; the documentation is correct afaik.

**Comment by antonengelhardt** [comment]
Same issue here when trying it with helm and k8s. I used [this repo](https://github.com/Arkaniad/matrix-chart) and it returns:

```
psycopg2.OperationalError: FATAL:  password authentication failed for user "synapse_user"
```

**Comment by antonengelhardt** [comment]
Using Synapse `v1.92.1`, Postgres Bitnami Chart `11.6.16` and a modified initdb-configmap.yaml:

```yaml
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-postgresql-initdb
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  matrix.sql: |
    CREATE USER {{ .Values.postgresql.username }} WITH PASSWORD '{{ .Values.postgresql.password }}';

    CREATE DATABASE {{ .Values.postgresql.database }}
      ENCODING 'UTF8'
      LC_COLLATE='C'
      LC_CTYPE='C'
      TEMPLATE=template0
      OWNER={{ .Values.postgresql.username }};

    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresql.database }} TO {{ .Values.postgresql.username }};
{{- end }}
```

Snippet from my `values.yaml`:

```yaml
postgresql:
  # Whether to deploy the stable/postgresql chart with this chart. If disabled, make sure PostgreSQL is available at the hostname below and credentials are configured below
  enabled: true

  username: synapse_user
  password: udzosd7pasdv7a0dc7q!
  database: synapse

  # Set this if postgresql.enabled = false
  hostname: ""
  port: 5432

  # Whether to connect to the database over SSL
  ssl: false
  # See https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS for documentation of these modes
  sslMode: prefer

  # Storage to allocate for stable/postgresql
  persistence:
    size: 8Gi

  # If postgresql.enabled, stable/postgresql will run the scripts in templates/postgresql/initdb-configmap.yaml
  # If using an external Postgres server, make sure to configure the database as specified at https://github.com/matrix-org/synapse/blob/master/docs/postgres.md
  initdbScriptsConfigMap: "{{ .Release.Name }}-postgresql-initdb"

  securityContext:
    enabled: true
    runAsUser: 1000
    fsGroup: 1000

# Synapse Kubernetes resource settings
synapse:
  image:
    repository: "matrixdotorg/synapse"
    tag: v1.92.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    federation:
      type: ClusterIP
      port: 80
  replicaCount: 1
  resources: {}
  # Configure timings for readiness, startup, and liveness probes here
  probes:
    readiness:
      timeoutSeconds: 5
      periodSeconds: 10
    startup:
      timeoutSeconds: 5
      periodSeconds: 5
      failureThreshold: 6
    liveness:
      timeoutSeconds: 5
      periodSeconds: 10

  # Does not work by default in all cloud providers, disable by default
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

    # Enable if your k8s environment allows containers to chuser/setuid
    # https://github.com/matrix-org/synapse/blob/96cf81e312407f0caba1b45ba9899906b1dcc098/docker/start.py#L196
    env: false

  # Labels to be appended to all Synapse resources
  labels:
    component: synapse

  # Prometheus metrics for Synapse
  # https://github.com/matrix-org/synapse/blob/master/docs/metrics-howto.md
  metrics:
    # Whether Synapse should capture metrics on an additional endpoint
    enabled: true
    # Port to listen on for metrics scraping
    port: 9092
    annotations: true

  extraVolumes: []


  extraVolumeMounts: []
```

Might be a silly mistake...

**Comment by satoshinotdead** [comment]
I get the same error on docker-compose.yml and I deleted the volume of database, all the containers, recreate them but I still can't start my server because of that.

```psycopg2.OperationalError: connection to server at "postgres" (10.10.10.2), port 5432 failed: FATAL:  password authentication failed for user "synapse"```

**Comment by antonengelhardt** [comment]
@richvdh The solution for me was to delete all volumes, the stateful set for Postgres and then it worked

**Comment by antonengelhardt** [comment]
Repost:

Using Synapse v1.92.1, Postgres Bitnami Chart 11.6.16 and a modified initdb-configmap.yaml:

```yaml
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-postgresql-initdb
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  matrix.sql: |
    CREATE USER {{ .Values.postgresql.username }} WITH PASSWORD '{{ .Values.postgresql.password }}';

    CREATE DATABASE {{ .Values.postgresql.database }}
      ENCODING 'UTF8'
      LC_COLLATE='C'
      LC_CTYPE='C'
      TEMPLATE=template0
      OWNER={{ .Values.postgresql.username }};

    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresql.database }} TO {{ .Values.postgresql.username }};
{{- end }}
```

Snippet from my values.yaml:

```yaml
postgresql:
  # Whether to deploy the stable/postgresql chart with this chart. If disabled, make sure PostgreSQL is available at the hostname below and credentials are configured below
  enabled: true

  username: synapse_user
  password: xxx
  database: synapse

  # Set this if postgresql.enabled = false
  hostname: ""
  port: 5432

  # Whether to connect to the database over SSL
  ssl: false
  # See https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS for documentation of these modes
  sslMode: prefer

  # Storage to allocate for stable/postgresql
  persistence:
    size: 8Gi

  # If postgresql.enabled, stable/postgresql will run the scripts in templates/postgresql/initdb-configmap.yaml
  # If using an external Postgres server, make sure to configure the database as specified at https://github.com/matrix-org/synapse/blob/master/docs/postgres.md
  initdbScriptsConfigMap: "{{ .Release.Name }}-postgresql-initdb"

  securityContext:
    enabled: true
    runAsUser: 1000
    fsGroup: 1000

# Synapse Kubernetes resource settings
synapse:
  image:
    repository: "matrixdotorg/synapse"
    tag: v1.92.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    federation:
      type: ClusterIP
      port: 80
  replicaCount: 1
  resources: {}
  # Configure timings for readiness, startup, and liveness probes here
  probes:
    readiness:
      timeoutSeconds: 5
      periodSeconds: 10
    startup:
      timeoutSeconds: 5
      periodSeconds: 5
      failureThreshold: 6
    liveness:
      timeoutSeconds: 5
      periodSeconds: 10

  # Does not work by default in all cloud providers, disable by default
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

    # Enable if your k8s environment allows containers to chuser/setuid
    # https://github.com/matrix-org/synapse/blob/96cf81e312407f0caba1b45ba9899906b1dcc098/docker/start.py#L196
    env: false

  # Labels to be appended to all Synapse resources
  labels:
    component: synapse

  # Prometheus metrics for Synapse
  # https://github.com/matrix-org/synapse/blob/master/docs/metrics-howto.md
  metrics:
    # Whether Synapse should capture metrics on an additional endpoint
    enabled: true
    # Port to listen on for metrics scraping
    port: 9092
    annotations: true

  extraVolumes: []


  extraVolumeMounts: []
```

Might be a silly mistake...
