### ISSUE TITLE
Default docker compose is broken out of the box

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5019]
Possibly related: https://github.com/matrix-org/synapse/issues/4147
Source: https://www.reddit.com/r/selfhosted/comments/b9lll6/helping_setting_up_riotim_docker/ek660zc/

It should probably show how to run it behind a reverse proxy, or do so itself. Would be nice to have a federation-ready template.

**Comment by johnchristopher** [comment]
I also would like a federation ready template with SSL termination on the reverse proxy.

This is the default template I am using right now but I can't federate (yet). Working without problems so far (+LE certs) .I have different networks because I want to be able to bring one down at any time without halting other services :
# Matrix server container
```yml
version: "3"

services:
  matrix:
    image: "matrixdotorg/synapse:v0.99.2"
    container_name: matrix
    volumes:                                                                                                                                                                                                      
      - ./data:/data                                                                                                                                                                                              
    environment:                                                                                                                                                                                                  
      - SYNAPSE_NO_TLS=1  # last time I checked the documentation it said this had to be set to 0 to allow federating                                                                                                                                                                                         
      - SYNAPSE_SERVER_NAME=matrix.domain.tld                                                                                                                                                        
      - SYNAPSE_ENABLE_REGISTRATION=1                                                                                                                                                                             
      - SYNAPSE_ALLOW_GUEST=1                                                                                                                                                                                     
      - SYNAPSE_REPORT_STATS=1                                                                                                                                                                                    
    labels:                                                                                                                                                                                                       
      - traefik.frontend.rule=Host:matrix.domain.tld                                                                                                     
      - traefik.frontend.entryPoints=https                                                                                                                                                                        
      - traefik.port=8008                                                                                                                                                                                         
      - traefik.backend=matrix                                                                                                                                                                                    
networks:                                                                                                                                                                                                         
  default:                                                                                                                                                                                                        
    external:                                                                                                                                                                                                     
      name: matrix
```
# Traefik service container
```yml
version: '3'

services:
  traefik:
    image: traefik:v1.7.7-alpine
    container_name: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jhnchr/traefik/traefik.toml:/traefik.toml
      - /home/jhnchr/traefik/acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:traefik.domain.tld
      - traefik.frontend.entryPoints=https
      - traefik.port=8080
      - traefik.frontend.auth.basic=admin:$$apr1$$
      - traefik.backend='traefik'

networks:
  default:
    external: 
      name: traefik
```
# Traefik service configuration (traefik.toml):
```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    passHostHeader=true
    [entryPoints.https.tls]
[acme]
email = "user@validmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging =true

[acme.httpChallenge]
entryPoint = "http"
```
