### ISSUE TITLE
synapse exited with code 0 without logs

### ISSUE THREAD

**Issue by Bastien-Bellino** [matrix-org/synapse#5201]
Hi,

I tried to install a matrix server for riot.im with a docker-compose but i had some errors.
At the start, I had the same problem of this post : https://github.com/matrix-org/synapse/issues/4830
I did the workaround, but now I have a "synapse exited with code 0" without logs.

Do you have any idea ? To see log for example.
Thanks for you help.

The docker-compose file :
```
version: '3.7'

services:
  riot:
    image: avhost/docker-matrix-riot
    container_name: riot
    restart: always
    networks:
      - web
      - internal
    volumes:
      - /data/riot:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.port=8765"
      - "traefik.entryPoint=https"
      - "traefik.backend=riot"
      - "traefik.frontend.rule=Host:myhost"

  synapse:
    image: matrixdotorg/synapse
    entrypoint: chown 901:901 /data
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=synapse.bastien-b.gq
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - SYNAPSE_NO_TLS=yes
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=synapse
      - POSTGRES_HOST=db_synapse
      - POSTGRES_USER=synapse
    volumes:
      - /data/synapse:/data
    depends_on:
      - db_synapse
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.port=8008"
      - "traefik.entryPoint=https"
      - "traefik.backend=synapse"
      - "traefik.frontend.rule=Host:myHost"

  db_synapse:
    image: postgres:latest
    container_name: db_synapse
    restart: always
    volumes:
      - /data/db_synapse:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=myPassword
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  web:
    external: true
  internal:
    external: false
```
