### ISSUE TITLE
Server notices feature is not provisioner-friendly

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#5535]
**Description:**

As brought up in https://github.com/matrix-org/matrix-hosted/issues/709#issuecomment-504879001, there's currently no way to set a custom message for the room except for the consent message. Additionally, it's possible for the user to be invited to the room and find no message waiting for them (problem discussed in the above issue), which can be really confusing first impressions.

Here are the problems with the feature I've identified:

- [ ] The user can be invited to the Server Notices room even if there isn't a message waiting for them.
- [ ] A custom message cannot be specified except for one requiring consent. Ideally another field would be added [in the config](https://github.com/matrix-org/synapse/blob/4f68188d0bbdb1966250375d34125572eb82a117/docs/sample_config.yaml#L1288) to set this.
- [ ] The sample config state that the Server Notices room is "a special room which cannot be left": https://github.com/matrix-org/synapse/blob/4f68188d0bbdb1966250375d34125572eb82a117/docs/sample_config.yaml#L1274 Whereas our documentation states that "having joined the room, the user can leave the room if they want": https://github.com/matrix-org/synapse/blob/master/docs/server_notices.md#user-experience

**Comment by anoadragon453** [comment]
> The user can be invited to the Server Notices room even if there isn't a message waiting for them.

@jaywink Could you provide the Synapse config used that caused this?

**Comment by jaywink** [comment]
Sorry, forgot to reply to this. This is the config:

```
server_notices:
   system_mxid_localpart: server
   system_mxid_display_name: "System Alerts"
   # system_mxid_avatar_url: "mxc://matrix.org/aNYGgqTuDhfXuKWDAkqbXXWL"
   room_name: "System Alerts"
```
