### ISSUE TITLE
Rely on external logrotate to rotate logs

### ISSUE THREAD

**Issue by dkowis** [matrix-org/synapse#5697]
**Description:**

Instead of using the rolling file handler, which does not do compresion, and leaves a gig of log files around, I suggest using a WatchedFileHandler

```yaml
handlers:
  file:
    class: logging.handlers.WatchedFileHandler
    formatter: precise
    filename: /var/log/matrix-synapse/homeserver.log
    filters: [context]
    encoding: utf8
```

This makes it easy to use with logrotate, which can provide compression and daily rotation, rather than log-size based rotation, which could result in all your logs vanishing in a day if something goes crazy.
