### ISSUE TITLE
Should not require TLS key with tls set to false

### ISSUE THREAD

**Issue by openscript** [matrix-org/synapse#5841]
### Description
The `tls_private_key_path` file is required even tls seems to be disabled in the `homeserver.yaml`.

### Steps to reproduce
1. Use the official docker image with synapse 1.2.1
1. Set the following configuration to the config: 
```
listeners:
  # TLS-enabled listener: for when matrix traffic is sent directly to synapse.
  #
  # Disabled by default. To enable it, uncomment the following. (Note that you
  # will also need to give Synapse a TLS key and certificate: see the TLS section
  # below.)
  #
  #- port: 8448
  #  type: http
  #  tls: true
  #  resources:
  #    - names: [client, federation]

  # Unsecure HTTP listener: for when matrix traffic passes through a reverse proxy
  # that unwraps TLS.
  #
  # If you plan to use a reverse proxy, please see
  # https://github.com/matrix-org/synapse/blob/master/docs/reverse_proxy.rst.
  #
  - port: 8008
    tls: false
    type: http
    x_forwarded: true

    resources:
      - names: [client, federation]
        compress: false
```
1. Start synapse:
```
synapse       | 2019-08-10 13:10:44,783 - root - 226 - WARNING - None - ***** STARTING SERVER *****
synapse       | 2019-08-10 13:10:44,791 - root - 227 - WARNING - None - Server /usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.2.1
synapse       | 2019-08-10 13:10:44,792 - root - 228 - INFO - None - Server hostname: chat.openscript.cloud
synapse       | 2019-08-10 13:10:44,793 - twisted - 254 - INFO - None - Redirected stdout/stderr to logs
synapse       | 2019-08-10 13:10:44,874 - twisted - 254 - ERROR -  - Traceback (most recent call last):
synapse       | 2019-08-10 13:10:44,875 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 113, in check_file
synapse       | 2019-08-10 13:10:44,876 - twisted - 254 - ERROR -  -     os.stat(file_path)
synapse       | 2019-08-10 13:10:44,876 - twisted - 254 - ERROR -  - FileNotFoundError: [Errno 2] No such file or directory: '/data/chat.openscript.tls.key'
synapse       | 2019-08-10 13:10:44,877 - twisted - 254 - ERROR -  - 
synapse       | 2019-08-10 13:10:44,877 - twisted - 254 - ERROR -  - During handling of the above exception, another exception occurred:
synapse       | 2019-08-10 13:10:44,877 - twisted - 254 - ERROR -  - 
synapse       | 2019-08-10 13:10:44,878 - twisted - 254 - ERROR -  - Traceback (most recent call last):
synapse       | 2019-08-10 13:10:44,878 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/_base.py", line 253, in start
synapse       | 2019-08-10 13:10:44,879 - twisted - 254 - ERROR -  -     refresh_certificate(hs)
synapse       | 2019-08-10 13:10:44,879 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/_base.py", line 208, in refresh_certificate
synapse       | 2019-08-10 13:10:44,880 - twisted - 254 - ERROR -  -     hs.config.read_certificate_from_disk(require_cert_and_key=True)
synapse       | 2019-08-10 13:10:44,880 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/config/tls.py", line 214, in read_certificate_from_disk
synapse       | 2019-08-10 13:10:44,880 - twisted - 254 - ERROR -  -     self.tls_private_key = self.read_tls_private_key()
synapse       | 2019-08-10 13:10:44,881 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/config/tls.py", line 454, in read_tls_private_key
synapse       | 2019-08-10 13:10:44,881 - twisted - 254 - ERROR -  -     private_key_pem = self.read_file(private_key_path, "tls_private_key_path")
synapse       | 2019-08-10 13:10:44,882 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 135, in read_file
synapse       | 2019-08-10 13:10:44,882 - twisted - 254 - ERROR -  -     cls.check_file(file_path, config_name)
synapse       | 2019-08-10 13:10:44,883 - twisted - 254 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 117, in check_file
synapse       | 2019-08-10 13:10:44,883 - twisted - 254 - ERROR -  -     % (file_path, config_name, e.strerror)
synapse       | 2019-08-10 13:10:44,884 - twisted - 254 - ERROR -  - synapse.config._base.ConfigError: Error accessing file '/data/chat.openscript.tls.key' (config for tls_private_key_path): No such file or directory
```
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: private homeserver

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: Synapse 1.2.1

- **Install method**: Official docker image
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Docker
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
