### ISSUE TITLE
URL preview whitelisting akin to url_preview_url_blacklist

### ISSUE THREAD

**Issue by dud1337** [matrix-org/synapse#6205]
In `homeserver.yaml` we have:
```yaml
url_preview_ip_range_blacklist:
...
url_preview_ip_range_whitelist:
...
url_preview_url_blacklist:
```
I propose adding
```yaml
url_preview_url_whitelist:
```
Using the same [urlparse](https://docs.python.org/2/library/urlparse.html#urlparse.urlsplit) scheme as the blacklist.

Instead of blacklisting 99% of domains, one could whitelist just a few - which might have dynamic IP addresses, or IPs that host multiple sites with potentially malicious/invasive owners.

Example:
```yaml
url_preview_url_whitelist:
    - netloc: 'my_site.com'
    - netloc: '*.my_site.com'
    - netloc: 'another_acceptable_site.com'
```
