### ISSUE TITLE
Support config fragments for docker image

### ISSUE THREAD

**Issue by ptman** [matrix-org/synapse#6662]
**Description:**

I'm using the very nice docker image of synapse and would like to follow the default configuration and only override specific parts of it. It seems that synapse supports config fragments in a directory (which the debian package seems to be [using](https://github.com/matrix-org/synapse/blob/master/debian/matrix-synapse.service#L10) ), but the docker image runs [start.py](https://github.com/matrix-org/synapse/blob/master/docker/start.py#L250) which doesn't have the relevant flags and doesn't allow passing them in.

**Comment by richvdh** [comment]
yeah; it would be good just to pass additional commandline args through to the synapse process.

**Comment by samuel-p** [comment]
For now you can overwrite the entrypoint like this to use multiple configs:

```
docker run --entrypoint "/usr/local/bin/python -m synapse.app.homeserver --config-path=/data/homeserver.yaml --config-path=/data/another-file.yaml" ...
```

or using `docker-compose`:

```
  synapse:
    image: matrixdotorg/synapse
    entrypoint:
      - /usr/local/bin/python
      - -m
      - synapse.app.homeserver
      - --config-path=/data/homeserver.yaml
      - --config-path=/data/another-file.yaml
```
