### ISSUE TITLE
[rfc] simplify reverse-proxy configuration requirements

### ISSUE THREAD

**Issue by cdaringe** [matrix-org/synapse#6930]
# Description

my server is configured as follows:

```yml
listeners:
  - port: 8448
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
```

my reverse proxy maps `my.host.com:443` / `https://my.host.com` => `8448`. it seems the system & federationtester.matrix.org demands that my federation requests go thru :8448, vs :443.

this is a bummer, because i'm serving federation resources off of :443.  the current recipe demands either:

- configuring a .well-known workflow, which is undesirable--my reverse-proxy configures this and is a blackbox
- using a SRV record, which i can't do, because my (sub)domains all have CNAMEs

# Discussion

is there a story around a single port for all traffic?
