### ISSUE TITLE
Account validity: admin account has expired

### ISSUE THREAD

**Issue by ukcb** [matrix-org/synapse#7292]
I start a script at irregular intervals for various tasks that require an admin account. I have activated the option for account validity configuration (synapse v1.12.x).

```
account_validity:
  enabled: true
  period: 6w
  renew_at: 1w
```

At some point my system admin was gone.

```
ROOM_ID: !xxxxxxxxxxxxx
{
    "errcode": "ORG_MATRIX_EXPIRED_ACCOUNT",
    "error": "User account has expired"
}
```

An admin's account shouldn't expire?
