### ISSUE TITLE
user_directory.notify_new_event and stats.notify_new_event exceptions

### ISSUE THREAD

**Issue by krystiancha** [matrix-org/synapse#7466]
### Description

I changed the user directory configuration. I flipped the `search_all_users` option to true.

Then, as the comment in config says, I ran the query linked in [this doc](https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md).

Now I get exceptions in my synapse logs.

https://gist.github.com/krystiancha/45d78bd0b4436f054090328a72186a7b

### Steps to reproduce

- change `search_all_users` option to true
- run the queries from the doc linked above
- restart synapse

### Version information

- **Homeserver**: self hosted

If not matrix.org:

- **Version**: 1.12.4

- **Install method**: pacman

- **Platform**: Arch Linux

**Comment by anoadragon453** [comment]
Thank you for your bug report. Can I ask whether you're running Synapse in [worker mode](https://github.com/matrix-org/synapse/blob/master/docs/workers.md)?

Possibly related: https://github.com/matrix-org/synapse/issues/7360

**Comment by krystiancha** [comment]
Thanks for the reply. I'm not running Synapse in worker mode. I'm running it via systemd unit provided with the package.

```
[Unit]
Description=Synapse Matrix homeserver
After=network-online.target
Requires=network-online.target

[Service]
Type=simple
User=synapse
Group=synapse
SyslogIdentifier=synapse
Environment=LANG=en_US.UTF-8
WorkingDirectory=/var/lib/synapse
ExecStart=/usr/bin/python3 -m synapse.app.homeserver --config-path=/etc/synapse/homeserver.yaml
ExecStop=/usr/bin/synctl stop /etc/synapse/homeserver.yaml
EnvironmentFile=-/etc/default/synapse

[Install]
WantedBy=multi-user.target
```

And I have only one listener in my `homeserver.yml`.

```
listeners:
   - port: 8008
     tls: false
     type: http
     x_forwarded: true
     bind_addresses: ['::1', '127.0.0.1']

     resources:
       - names: [client, federation]
         compress: false
```
