### ISSUE TITLE
Changing server_notices_mxid_avatar_url does not change notices user avatar image

### ISSUE THREAD

**Issue by ptman** [matrix-org/synapse#7478]
### Description

The server notices user (and room) avatar doesn't work. Instead riot shows an S.

### Steps to reproduce

```yaml
server_notices:
  system_mxid_localpart: 'notices'
  system_mxid_display_name: 'Server Notices'
  system_mxid_avatar_url: 'mxc://.../...'
  room_name: 'Server Notices'
```

### Version information

- **Version**: 1.12.4+bionic1
- **Install method**: apt
- **Platform**: ubuntu 18.04

**Comment by anoadragon453** [comment]
Hm, I'm unable to reproduce this locally on the `release-v1.12.4` branch or `develop`.

Using config:

```yaml
server_notices:
  system_mxid_localpart: 'notices'
  system_mxid_display_name: 'Server Notices'
  system_mxid_avatar_url: 'mxc://half-shot.uk/6fc3fb176d5246f1e7cf7d89ad4248b8'
  room_name: 'Server Notices'
```

And sending command:

```bash
curl -X POST -H 'Authorization: Bearer xxx' -i http://localhost:8008/_synapse/admin/v1/send_server_notice --data '{
    "user_id": "@bob:localhost",
    "content": {
        "msgtype": "m.text",
        "body": "Sup yo"
    }
}'
```

Things seem to work as they should:

![image](https://user-images.githubusercontent.com/1342360/81705368-e0f5c680-9466-11ea-9831-6440f238f8c8.png)

One thing I did notice is that editing `system_mxid_display_name` and `system_mxid_avatar_url` without setting `system_mxid_localpart` to a new localpart doesn't change the display name or avatar url. Indeed it seems those are only set when creating a new Server Notices room with a user:

https://github.com/matrix-org/synapse/blob/28c98e51ffa166bd717646b0b34228e59f253485/synapse/server_notices/server_notices_manager.py#L125-L139

Is that what you're referring to?
