### ISSUE TITLE
Server notice user's avatar and displayname are only set on initial creation of the user

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7494]
If you've already created a server notices user, say with the following config:

```yaml
server_notices:
  system_mxid_localpart: 'notices'
  system_mxid_display_name: 'Server Notices'
  system_mxid_avatar_url: 'mxc://example.com/abcde12345'
  room_name: 'Server Notices'
```

change either `system_mxid_display_name`  or `system_mxid_avatar_url` will not update the user's avatar or display name. These are only set on initial creation of the user, thus changing `system_mxid_localpart` will apply the changes, but in the process create a new user.

The code for setting the displayname and avatar is:

https://github.com/matrix-org/synapse/blob/28c98e51ffa166bd717646b0b34228e59f253485/synapse/server_notices/server_notices_manager.py#L125-L139

Instead, Synapse should check to see if the displayname or avatar has changed after a server restart, and update them accordingly.
