### ISSUE TITLE
document how to configure prometheus for workers

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7773]
#7357 talks about setting up the synapse end, but I don't think we have anything for the prometheus end.

**Comment by richvdh** [comment]
it should look something like this:

```
  - job_name: "synapse"
    scrape_interval: 15s
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: ["localhost:9092"]
        labels:
          instance: "sw1v.org"
          job: "master"
          index: 1
      - targets: ["localhost:8283"]
        labels:
          instance: "sw1v.org"
          job: "synchrotron"
          index: 1
```
