### ISSUE TITLE
Internal server error when trying to log in with OIDC when external ID is a number

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#7795]
[`get_user_by_external_id`](https://github.com/matrix-org/synapse/blob/bd6dc17221741d4ceae05ae769a70696ae939336/synapse/storage/data_stores/main/registration.py#L390-L408) retrieves an MXID from the ID sent by the authentication portal when using SSO.

In this function, we expect `external_id` to be a string, however we don't make sure the SSO portal returns with one. We should either add a check to both of the two places this function is called from to make sure the external ID is a string, or change that function to do that (e.g. if the ID isn't a string, try to cast it as such and error in a nicer way if it's not possible).

Sentry issue: https://sentry.matrix.org/sentry/synapse-modular/issues/116450/

**Comment by babolivier** [comment]
As a sidenote, the main occurrence of that is if the localpart is a number, in which case we'll likely also run into other issues given Synapse reserves such localparts to guest users.

**Comment by jaller94** [comment]
As a user trying to log in, I get this "Internal server error" page on the callback page.
![Screenshot_2020-07-07_11-33-24](https://user-images.githubusercontent.com/10872136/86760827-cf373680-c045-11ea-9eaa-c73443f23d98.png)

**Comment by jaller94** [comment]
The synapse OpenID config I used on Modular was:

```
oidc_config:
   enabled: true
   discover: false
   issuer: "https://github.com/"
   client_id: "69…"
   client_secret: "60…"
   authorization_endpoint: "https://github.com/login/oauth/authorize"
   token_endpoint: "https://github.com/login/oauth/access_token"
   userinfo_endpoint: "https://api.github.com/user"
   scopes: ["read:user"]
   user_mapping_provider:
     config:
       subject_claim: "id"
       localpart_template: "{{ user.login }}"
       display_name_template: "{{ user.name }}"
```
