### ISSUE TITLE
document, or get rid of, the custom prometheus rules

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7917]
our grafana dashboard (that we publish in contrib) relies on a few custom prometheus rules (particularly for the "Event Persist Rates" section). We should really either document them, or update the dashboard not to depend on them.

**Comment by richvdh** [comment]
the custom rules in question are:

```
groups:
- name: synapse
  rules:
  - record: synapse_http_server_requests:method
    expr: sum without(servlet, tag) (synapse_http_server_requests)
    labels:
      servlet: ""
  - record: synapse_http_server_requests:servlet
    expr: sum without(method) (synapse_http_server_requests)
    labels:
      method: ""
  - record: synapse_http_server_response_ru_time_seconds
    expr: synapse_http_server_response_ru_utime_seconds + synapse_http_server_response_ru_stime_seconds
  - record: synapse_federation_client_sent
    expr: synapse_federation_client_sent_edus + 0
    labels:
      type: EDU
  - record: synapse_federation_client_sent
    expr: synapse_federation_client_sent_pdu_destinations:count + 0
    labels:
      type: PDU
  - record: synapse_federation_client_sent
    expr: sum without(type) (synapse_federation_client_sent_queries)
    labels:
      type: Query
  - record: synapse_federation_server_received
    expr: synapse_federation_server_received_edus + 0
    labels:
      type: EDU
  - record: synapse_federation_server_received
    expr: synapse_federation_server_received_pdus + 0
    labels:
      type: PDU
  - record: synapse_federation_server_received
    expr: sum without(type) (synapse_federation_server_received_queries)
    labels:
      type: Query
  - record: synapse_federation_transaction_queue_pending
    expr: synapse_federation_transaction_queue_pending_edus + 0
    labels:
      type: EDU
  - record: synapse_federation_transaction_queue_pending
    expr: synapse_federation_transaction_queue_pending_pdus + 0
    labels:
      type: PDU
  - record: synapse_storage_events_persisted_by_source_type
    expr: sum without(type, origin_type, origin_entity) (synapse_storage_events_persisted_events_sep{origin_type="remote"})
    labels:
      type: remote
  - record: synapse_storage_events_persisted_by_source_type
    expr: sum without(type, origin_type, origin_entity) (synapse_storage_events_persisted_events_sep{origin_entity="*client*",origin_type="local"})
    labels:
      type: local
  - record: synapse_storage_events_persisted_by_source_type
    expr: sum without(type, origin_type, origin_entity) (synapse_storage_events_persisted_events_sep{origin_entity!="*client*",origin_type="local"})
    labels:
      type: bridges
  - record: synapse_storage_events_persisted_by_event_type
    expr: sum without(origin_entity, origin_type) (synapse_storage_events_persisted_events_sep)
  - record: synapse_storage_events_persisted_by_origin
    expr: sum without(type) (synapse_storage_events_persisted_events_sep)
```

I've not gone through to check which of those are used by the dashboard.
