### ISSUE TITLE
Docker matrixdotorg/synapse:latest: libpython3.7m.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by jaltek** [matrix-org/synapse#8038]
### Description

Tried to start the docker image matrixdotorg/synapse:latest via docker-compose and getting the following error:
```
synapse_1     | /usr/local/bin/python: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
synapse_synapse_1 exited with code 127
```

### Steps to reproduce

- Start the matrixdotorg/synapse:latest via docker-compose or docker directly

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrixdotorg/synapse:latest

If not matrix.org: 

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: https://hub.docker.com/layers/matrixdotorg/synapse/latest/images/sha256-f66fa7b3bf5250d14d23c847d48cbabbe58c4d26217250dac2b0b90975a38731?context=explore

- **Install method**: Docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 18.04.4 LTS / Docker 19.03.6
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by jaltek** [comment]
Additional Information: matrixdotorg/synapse:v1.17.0 works perfectly.

**Comment by richvdh** [comment]
It seems to work here:

```
rav@fred:~/tmp$ docker pull  matrixdotorg/synapse:latest 
latest: Pulling from matrixdotorg/synapse
Digest: sha256:f66fa7b3bf5250d14d23c847d48cbabbe58c4d26217250dac2b0b90975a38731
Status: Image is up to date for matrixdotorg/synapse:latest
docker.io/matrixdotorg/synapse:latest

rav@fred:~/tmp$ docker run --rm -it -v `pwd`/tmp:/data -e SYNAPSE_SERVER_NAME=localhost -e SYNAPSE_REPORT_STATS=yes matrixdotorg/synapse:latest generate
Creating log config /data/localhost.log.config
Generating config file /data/homeserver.yaml
Generating signing key file /data/localhost.signing.key
A config file has been generated in '/data/homeserver.yaml' for server name 'localhost'. Please review this file and customise it to your needs.

rav@fred:~/tmp$ docker run --rm -it -v `pwd`/tmp:/data -p 18008:8008 matrixdotorg/synapse:latest
Starting synapse with config file /data/homeserver.yaml
...
```

please can you give more information on how to reproduce this?

**Comment by jaltek** [comment]
@richvdh Thanks. Yes, your examples worked for me also.

I'm using the following docker-compose.yml

```
version: '3'
services:
  synapse:
    build:
        context: ./
        dockerfile: Dockerfile
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - ./etc:/etc
      - ./data:/data
    depends_on:
      - synapse-db
    ports:
      - 8008:8008/tcp

  synapse-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - ./schemas:/var/lib/postgresql/data
```
