### ISSUE TITLE
Docs for workers setup in docker are missing

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/synapse#8053]
Hi guys!
I'd like to try setting up workers, as my instance is having veery big delays in message delivery, but in docker it's totally other setup than outside of docker as far as I can see.
DOCS ARE MISSING!
I'm having trouble figuring out what should I do.
Only thing I know is I should set `SYNAPSE_WORKER` to other class name.

**Comment by clokep** [comment]
The documentation should be roughly the same, but you would need to run each Docker container with a different configuration (see the [documentation for running Docker](https://github.com/matrix-org/synapse/blob/master/docker/README.md)). The configuration file can be specified via `SYNAPSE_CONFIG_DIR` / `SYNAPSE_CONFIG_PATH` environment variables. There's also a `SYNAPSE_WORKER` which may or may not be helpful depending on how much of the configuration needs to be overwritten.

Generally it is best to request help in #synapse:matrix.org.

**Comment by JuniorJPDJ** [comment]
I asked for help on #synapse:matrix.org and noone answered. I actually asked at least 2 times with few days interval.
What config file do I need to specify in `SYNAPSE_CONFIG_PATH`? One which would be in `workers/` dir in normal setup?

**Comment by clokep** [comment]
> What config file do I need to specify in `SYNAPSE_CONFIG_PATH`? One which would be in `workers/` dir in normal setup?

Whatever configuration you want that server to be running under. If you expect it to be a worker, then it would be one of the ones that has a worker configuration.

**Comment by JuniorJPDJ** [comment]
Ok, If it's worker's, then It doesn't work ;)
I created container:
```
synapse_worker:
    build: ../matrix/synapse-shared-secret-auth
    volumes:
      - ./data/synapse:/data
      - ./data/mautrix-telegram/registration.yaml:/data/mautrix-telegram-registration.yaml:ro
      - ./data/mautrix-facebook/registration.yaml:/data/mautrix-facebook-registration.yaml:ro
      - ./data/mx-puppet-discord/discord-registration.yaml:/data/mx-puppet-discord-registration.yaml:ro
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker  # without this also doesn't work
      SYNAPSE_CONFIG_PATH: /data/workers/worker1.yaml
```

Worker config looks like this:

```
worker_app: synapse.app.generic_worker
worker_name: worker1

# The replication listener on the main synapse process.
worker_replication_host: synapse
worker_replication_http_port: 9093

worker_listeners:
 - type: http
   port: 8083
   resources:
     - names:
       - client
       - federation

worker_log_config: /data/matrix.test.juniorjpdj.pl.log.config
```

And I'm getting error like main config file wasn't loaded:
```
dcu synapse_worker
Recreating test-matrix_synapse_worker_1 ... done
Attaching to test-matrix_synapse_worker_1
synapse_worker_1     | 
synapse_worker_1     | Missing mandatory `server_name` config option.
synapse_worker_1     | 
test-matrix_synapse_worker_1 exited with code 1
```
