### ISSUE TITLE
syslogidentifier not available in container task

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/synapse#8068]
I have a container with synapse and no systemd and have no way of setting the identifier. Now it logs to syslog server as journal:

I am having this in the logging config

```
handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
        filename: /data/homeserver.log
        maxBytes: 104857600
        backupCount: 10
        filters: [context]
        encoding: utf8
    syslog:
        class: logging.handlers.SysLogHandler
        formatter: syslog
        address: '/dev/log'
    console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]
```

Maybe useful
https://stackoverflow.com/questions/4261253/how-do-i-set-the-ident-string-when-using-logging-sysloghandler-in-python-2-6
