### ISSUE TITLE
If the TLS private key isn't readable, synapse just exits with code 0

### ISSUE THREAD

**Issue by xuhdev** [matrix-org/synapse#8460]
### Description

When the private key specified by `tls_private_key_path` is not readable, synapse simply exits with code 0.

### Steps to reproduce

- In `homeserver.yaml`, have `no_tls` set to `False` and ` tls_private_key_path` set to a private key (such as `/etc/letsencrypt/live/my.matrix.server/privkey.pem`)
- Ensure that user `matrix-synapse` does not have the permission to read the private key.
- Run

  ```
  sudo -u matrix-synapse /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/
  ```

The process simply exits silently without any error code.

### Version information

Output of
```
$ curl http://localhost:8008/_synapse/admin/v1/server_version
```

is 

```
{
    "python_version": "3.8.2",
    "server_version": "1.20.1"
}
```

- **Install method**:

Ubuntu 20.04, from the synapse official repo via `apt`.

**Comment by richvdh** [comment]
Can you share your logging configuration?

**Comment by xuhdev** [comment]
```yaml
# Log configuration for Synapse.
#
# This is a YAML file containing a standard Python logging configuration
# dictionary. See [1] for details on the valid settings.
#
# [1]: https://docs.python.org/3.7/library/logging.config.html#configuration-dictionary-schema

version: 1

formatters:
    precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:
    file:
        class: logging.handlers.TimedRotatingFileHandler
        formatter: precise
        filename: /var/log/matrix-synapse/homeserver.log
        when: midnight
        backupCount: 3  # Does not include the current log file.
        encoding: utf8

    # Default to buffering writes to log file for efficiency. This means that
    # will be a delay for INFO/DEBUG logs to get written, but WARNING/ERROR
    # logs will still be flushed immediately.
    buffer:
        class: logging.handlers.MemoryHandler
        target: file
        # The capacity is the number of log lines that are buffered before
        # being written to disk. Increasing this will lead to better
        # performance, at the expensive of it taking longer for log lines to
        # be written to disk.
        capacity: 10
        flushLevel: 30  # Flush for WARNING logs as well

    # A handler that writes logs to stderr. Unused by default, but can be used
    # instead of "buffer" and "file" in the logger handlers.
    console:
        class: logging.StreamHandler
        formatter: precise

loggers:
    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO

    twisted:
        # We send the twisted logging directly to the file handler,
        # to work around https://github.com/matrix-org/synapse/issues/3471
        # when using "buffer" logger. Use "console" to log to stderr instead.
        handlers: [file]
        propagate: false

root:
    level: INFO

    # Write logs to the `buffer` handler, which will buffer them together in memory,
    # then write them to a file.
    #
    # Replace "buffer" with "console" to log to stderr instead. (Note that you'll
    # also need to update the configuation for the `twisted` logger above, in
    # this case.)
    #
    handlers: [buffer]

disable_existing_loggers: false
```
