### ISSUE TITLE
SAML displayName not shown in client

### ISSUE THREAD

**Issue by localguru** [matrix-org/synapse#8478]
### Description

We use Shibboleth to authenticate our users at synapse. The IDP attributes `uid`, `email` and `displayName` are passed cleanly to synapse. However the `displayName`attribute does not appear in the user profile settings of any client. The email attribute is set in the user profile. Also the correct `displayName` is shown in the upper left corner (see screenshot below), but not in the profile settings.

### Steps to reproduce

- initial login (account creation) via SAML to synapse
- displayName is not shown in profile settings

 expected:
 - displayName should be shown in profile settings

### Version information

matrix-synapse-py3 1.20.1+bionic1 on Ubuntu 18.04 LTS (package from packages.matrix.org/debian/ )

/etc/matrix-synapse/homeserver.yaml
```
saml2_config:
  sp_config:
    metadata:
      remote:
        - url: https://shibboleth-test.uni-bielefeld.de/idp/shibboleth

    accepted_time_diff: 5
      
    service:
       sp:
         required_attributes: ["uid", "email", "displayName"]
         optional_attributes: ["eduPersonPrincipalName"]
         
         ui_info:
           display_name:
             - lang: de
               text: "Matrix"
           description:
             - lang: de
               text: "Matrix der Universitaet Bielefeld v014"
           information_url:
             - lang: de
               text: "http://sp.information.url/"
           privacy_statement_url:
             - lang: en
               text: "http://sp.privacy.url/"
           logo:
             text: "http://sp.logo.url/"
             width: "100"
             height: "100"

    description: ["Matrix Universitaet Bielefeld", "en"]
    name: ["Matrix Universitaet Bielefeld", "en"]
    key_file: /etc/matrix-synapse/matrix_uni-bielefeld_de.key
    cert_file: /etc/matrix-synapse/matrix_uni-bielefeld_de.crt
    encryption_keypairs:
      - key_file: /etc/matrix-synapse/matrix_uni-bielefeld_de.key
        cert_file: /etc/matrix-synapse/matrix_uni-bielefeld_de.crt
    attribute_map_dir: /etc/matrix-synapse/saml2-attribute-maps
  
    organization:
      name: KIT
      display_name:
        - ["KIT der Universitaet Bielefeld", "en"]
      url: "https://www.uni-bielefeld.de/kit/"
  
    contact_person:
      - given_name: Marcus
        sur_name: "Schopen"
        email_address: ["marcus.schopen@uni-bielefeld.de"]
        contact_type: technical
```

/etc/matrix-synapse/saml2-attribute-maps/map.py
```
MAP = {
    "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
    "fro": {
        'urn:oid:0.9.2342.19200300.100.1.1': 'uid',
        'urn:oid:0.9.2342.19200300.100.1.3': 'email',
        'urn:oid:2.16.840.1.113730.3.1.241': 'displayName',
    },
    "to": {
        'uid': 'urn:oid:0.9.2342.19200300.100.1.1',
        'email': 'urn:oid:0.9.2342.19200300.100.1.3',
        'displayName': 'urn:oid:2.16.840.1.113730.3.1.241',
    },
}
```

/var/log/matrix-synapse/homeserver.log
```
2020-10-06 15:38:48,134 - synapse.handlers.saml_handler - 210 - INFO - POST-227 - SAML2 mapped attributes: {'uid': ['gtestfall'], 'email': ['georg.testfall@mail-i.uni-bielefeld.de'], 'displayName': ['Georg Testfall']}
```
postgres:
```
synapse=# select * from profiles;

           user_id            |  displayname   | avatar_url 
------------------------------+----------------+------------
[...]
 gtestfall                    | Georg Testfall | 
(4 rows)
```
```
select * from users;
                      name                      |                        password_hash                         | creation_ts | admin | upgrade_ts | is_guest | appservice_id | consent_version | consent_server_notice_sent | user_type | deactivated | shadow_banned 
------------------------------------------------+--------------------------------------------------------------+-------------+-------+------------+----------+---------------+-----------------+----------------------------+-----------+-------------+---------------
[...]
 @gtestfall:uni-bielefeld.de                    |                                                              |  1601989626 |     0 |            |        0 |               |                 |                            |           |           0 | f
(4 rows)
```

Screenshot Client, tested in desktop client and https://app.element.io

![saml_display_name](https://user-images.githubusercontent.com/8544984/95236429-3613e980-0807-11eb-9689-ca8cbbbc1af7.png)
