### ISSUE TITLE
Alias creation allow/deny lists …

### ISSUE THREAD

**Issue by fooness** [matrix-org/synapse#8703]
Hello everyone. I’ve been asking this on #synapse for about one week now, unfortunately without any advice … so please allow me to open this questions and/or discussion here.

We would like to allow our users to add local addresses to their rooms. No public addresses, though.

In addition to that, we would like to specifically deny certain prefixes for local addresses (unless for one specific admin-account), or vice versa we could also allow only certain prefixes for all users.

For example, all users (unless admin-account) are allowed to create aliases for their rooms, but only aliases starting with e.g. underscore `_` … is this possible somehow via the `alias_creation_rules`?

```
alias_creation_rules:
  - user_id: "@admin-account:example.org"
    alias: "*"
    room_id: "*"
    action: allow
  - user_id: "*"
    alias: "_*:example.org"
    room_id: "*"
    action: allow
```

**Comment by erikjohnston** [comment]
There are a number of different, but related, concepts here:

1. Adding a local alias mapping to the server.
2. Publishing the room in the server's public room list.
3. Room moderators/admins can add aliases to the `m.room.canonical_alias` state event in the room, so that other users can see that the alias exists and (probably) points to the room.

The `alias_creation_rules` config options only effects 1, `room_list_publication_rules` only effects 2, and currently there is no dedicated option for 3. The latter is something that in general you can't control (if done by remote users), but you could write a plugin using `third_party_event_rules` to stop users from doing so. We could also potentially add a dedicated option (or extend `alias_creation_rules`) to try and stop it, but I'm a bit unsure if that is something we want to do. Is that a feature you'd like?

> In addition to that, we would like to specifically deny certain prefixes for local addresses (unless for one specific admin-account), or vice versa we could also allow only certain prefixes for all users.

```yaml
alias_creation_rules:
  - user_id: "@admin-account:example.org"
    action: allow
  - alias: "#_*:example.org"
    action: allow
```

should only allow users to create aliases starting with an `_`, e.g. `#_foo:example.com`.
