### ISSUE TITLE
Synapse config options in caches.per_cache_factors don't change cache limits

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#8748]
I try to find way for increase size limit of `_get_joined_profile_from_event_id` cache in Synapse 1.22.1.
With default setup via Prometheus stats I see that it is limited to 5K items, so I fill those params in `homeserver.yaml` file:
```
event_cache_size: 900K

caches:
   #global_factor: 1.5
   global_factor: 4.0
   per_cache_factors:
     _get_joined_profile_from_event_id: 50.0
```
and restart Synapse, but see that the limit is not changed, here is the chart with restart event at ~11:05:
![image](https://user-images.githubusercontent.com/336662/98927020-113b2200-24e9-11eb-8a78-d579a351446e.png)

Why increasing `per_cache_factors` doesn't increase 5K limit - is this a Synapse issue, or I must configure this limit in some other place?
