### ISSUE TITLE
OIDC authenticator does use the user id sent by the provider if it contains uppercases

### ISSUE THREAD

**Issue by tmortagne** [matrix-org/synapse#9315]
Synapse version: 1.26.0
Client: https://app.element.io

When the OIDC provider return "ThomasMortagne" as subject I'm asked to provide the user id after the auth ("`Please pick your username:`"). When I try to enter "ThomasMortagne" in this form I get "`Invalid username. Only the following characters are allowed: lowercase letters, digits, ., _, -, /, =`" so I guess that's why it did not use it. But then I would have expected it to try to clean up the subject automatically for simple case like upper vs lower case. At the very least It should explain why it's asking for the id.

This sounds like quite a constraint, but I don't see any reference to it in the documentation, so it's possible I'm completely wrong.

**Comment by clokep** [comment]
Matrix IDs must be all lower-case.

Are you using a custom mapping provider? v1.26.0 includes a feature to prompt people to enter their username (instead of automatically using the one from SSO), which I think it is enabled by default.

I see you provided a config in #9316:

```yaml
oidc_providers:
  - idp_id: adm
    idp_name: "My Provider"
    issuer: "https://myhost/oidc/"
    client_id: "matrix"
    client_secret: "dontcare"
    scopes: ["openid", "profile", "email"]
```

Take a look at the [`mapping_provider`](https://github.com/matrix-org/synapse/blob/ccb9616f26413db4b829536f454923f9edb75040/docs/sample_config.yaml#L1779-L1812) key, maybe you want something like:

```yaml
oidc_providers:
  - idp_id: adm
    idp_name: "My Provider"
    issuer: "https://myhost/oidc/"
    client_id: "matrix"
    client_secret: "dontcare"
    scopes: ["openid", "profile", "email"]
    mapping_provider:
      config:
        localpart_template: "{{ user.login }}"
```

**Comment by tmortagne** [comment]
> Are you using a custom mapping provider?

No I don't actually configure anything for the mapping, just using the default behavior.

> v1.26.0 includes a feature to prompt people to enter their username (instead of automatically using the one from SSO), which I think it is enabled by default.

OK that's the part I missed and which was indeed clearly indicated in the documentation.

> Matrix IDs must be all lower-case.

So my only solution is to find a way on provider side to send a subject compatible with Matrix id constraints ?

**Comment by clokep** [comment]
> > Matrix IDs must be all lower-case.
> 
> So my only solution is to find a way on provider side to send a subject compatible with Matrix id constraints, right ?

No, the default mapping provider should convert whatever is used as the `localpart_template` into a valid MXID automatically.

**Comment by tmortagne** [comment]
> No, the default mapping provider should convert whatever is used as the localpart_template into a valid MXID automatically.

OK sounds great ! One last thing, it's not clear so me what "login" is since the documentation indicate that "`the Jinja2 templates are given a 'user' variable, which is set to the claims returned by the UserInfo Endpoint and/or in the ID Token.`" and there is no such claim in OIDC. But maybe "login" a field injected by Synapse with the value of the sub ?

**Comment by clokep** [comment]
What exactly is available on the `user` variable depends on the claims that are provided by your OIDC provider, `sub` is a common one which could be accessed via `user.sub`.

**Comment by tmortagne** [comment]
Yes I know about `sub`, I was just wondering why you were suggesting to use `login`.

**Comment by tmortagne** [comment]
So I tried with:

```
oidc_providers:
  - idp_id: adm
    idp_name: "My Provider"
    issuer: "https://myhost/oidc/"
    client_id: "matrix"
    client_secret: "dontcare"
    scopes: ["openid", "profile", "email"]
    user_profile_method: "userinfo_endpoint"
    mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
```

(with the "preferred_username" claim containing "ThomasMortagne")

But it keeps asking me for the id.

The log does not really give much hint on why (but at least it seem it did use the userinfo endpoint thanks to `user_profile_method: "userinfo_endpoint"`):

```
2021-02-04 15:34:35,152 - synapse.http.client - 429 - INFO - GET-7 - Received response to POST https://myhost/oidc/token: 200
2021-02-04 15:34:35,392 - synapse.http.client - 429 - INFO - GET-7 - Received response to GET https://myhost/oidc/userinfo: 200
2021-02-04 15:34:35,398 - synapse.handlers.sso - 501 - INFO - GET-7 - Recorded registration session id **************
2021-02-04 15:34:35,399 - synapse.http.server - 120 - INFO - GET-7 - <XForwardedForRequest at 0x7fb6005265f8 method='GET' uri='/_synapse/oidc/callback?code=****&state=****' clientproto='HTTP/1.1' site='8008'> redirect to b'/_synapse/client/pick_username'
```
