### ISSUE TITLE
enable jwt doesnt work - Matrix Homeserver

### ISSUE THREAD

**Issue by KineticFox** [matrix-org/synapse#9354]
did everything mentioned in here : https://github.com/matrix-org/synapse/blob/develop/docs/jwt.md
but still if i curl my homeserver there is only type m.login.password

i i curl with a valid jwt-token genereatd with the paython lib i got as response type : m.login.password

i got no errors in my logfile, installed PyJWT

i dont know what to do

**Comment by clokep** [comment]
What version of synapse are you running? Can you provide the redacted jwt config you're using? Ensure you restart synapse after making config changes.

**Comment by KineticFox** [comment]
running version 1.25 , restarted after config change 

```
jwt_config:
    enabled: true
    secret: "my generated secret"
    algorithm: "HS256"
```
