### ISSUE TITLE
sending not possible after upgrade to v1.27; nginx runs into timeout

### ISSUE THREAD

**Issue by a000a** [matrix-org/synapse#9422]
My clients cannot send events to the server after upgrading from `v1.26.0` to `v1.27.0`

receiving messages from other homeservers works fine

nginx throws an error, but I'm not sure if it hasn't been before
```
upstream timed out (110: Unknown error) while reading response header from upstream, client: 192.168.181.23, server: matrix.a2sc.eu, request: "PUT /_matrix/client/r0/rooms/!abc%3Ac.a2sc.eu/send/m.room.encrypted/m123 HTTP/2.0", upstream: "http://[::1]:8008/_matrix/client/r0/rooms/!abc%3Ac.a2sc.eu/send/m.room.encrypted/m123", host: "matrix.a2sc.eu"
````

nginx config:
```
server {
    server_name matrix.a2sc.eu;

    listen 443 ssl;
    listen [::]:443 ssl;
    listen 8448 ssl default_server;
    listen [::]:8448 ssl  default_server;

    include /etc/nginx/ssl.conf;

    root /var/www/;
    index index.html index.htm;

    client_max_body_size 512M;
    location / {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr; 
        #proxy_set_header Host $host;
        #proxy_set_header X-Real-IP $remote_addr;
    }

    location ~* ^(\/_matrix|\/_synapse\/client) {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        client_max_body_size 50M;
    }
    location /.well-known/matrix/ {
        add_header 'Content-Type' 'application/json'; # Required to tell the requesting entity we're replying with JSON data
        add_header 'Access-Control-Allow-Origin' '*'; # Required to allow loading from Riot Web through CLI
        # The following settings are Optional
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        autoindex on;
        autoindex_exact_size on;
        autoindex_format json;
        autoindex_localtime on;
        alias /var/www/.well-known/matrix/;
    }
}

```

synapse config:
```
server_name: "c.a2sc.eu"
pid_file: /etc/synapse/homeserver.pid
web_client_location: https://c.a2sc.eu/
public_baseurl: https://matrix.a2sc.eu/
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
  - port: 9093
    bind_address: '127.0.0.1'
    type: http
    resources:
     - names: [replication]
admin_contact: 'mailto:matrix_admin@a2sc.eu'
limit_usage_by_mau: false
mau_stats_only: true
limit_remote_rooms:
retention:
federation_client_minimum_tls_version: 1.2
acme:
    enabled: false
    port: 80
    bind_addresses: ['::', '0.0.0.0']
    reprovision_threshold: 30
    domain: matrix.a2sc.eu
    account_key_file: /etc/synapse/acme_account.key
federation_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '169.254.0.0/16'
  - '::1/128'
  - 'fe80::/64'
  - 'fc00::/7'
caches:
   per_cache_factors:
database:
  name: psycopg2
  args:
        user: synapse_user
        password: abc
        database: synapse
        host: /run/postgresql
        cp_min: 5
        cp_max: 10
log_config: "/etc/synapse/log_config.yaml"
media_store_path: "/var/synapse/media_store"
max_upload_size: 5120M
dynamic_thumbnails: true
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '169.254.0.0/16'
  - '::1/128'
  - 'fe80::/64'
  - 'fc00::/7'
url_preview_url_blacklist:
  - username: '*'
  - netloc: 'google.com'
  - netloc: '*.google.com'
max_spider_size: 10M
url_preview_accept_language:
enable_registration: true
account_validity:
enable_3pid_lookup: true
allow_guest_access: false
default_identity_server: https://matrix.org
account_threepid_delegates:
    msisdn: https://vector.im
auto_join_rooms:
enable_metrics: true
metrics_flags:
report_stats: false
app_service_config_files:
macaroon_secret_key: "abc"
form_secret: "abc"
signing_key_path: "/etc/synapse/signing.key"
old_signing_keys:
  ed25519:a_wIti: {key: "abc", expired_ts: 1594651779000 }
  ed25519:auto:   {key: "abc", expired_ts: 1597269600000 }
trusted_key_servers:
  - server_name: "matrix.org"
    verify_keys:
            "ed25519:auto": "abc"
key_server_signing_keys_path: "/etc/synapse/key_server_signing.key"
saml2_config:
  user_mapping_provider:
    config:
oidc_config:
  user_mapping_provider:
    config:
      localpart_template: "{{ user.preferred_username }}"
sso:
password_config:
   policy:
email:
  smtp_host: mail.abc.de
  smtp_port: 587
  smtp_user: "matrix@a2sc.eu"
  smtp_pass: "abc"
  require_transport_security: true
  notif_from: "c.a2sc.eu-%(app)s homeserver <matrix@a2sc.eu>"
  enable_notifs: true
  notif_for_new_users: false
  client_base_url: "https://c.a2sc.eu"
  validation_token_lifetime: 30m
  template_dir: "/usr/lib/python3.9/site-packages/synapse/res/templates"
password_providers:
  - module: "shared_secret_authenticator.SharedSecretAuthenticator"
    config:
      sharedSecret: "abc"
push:
  include_content: true
spam_checker:
enable_group_creation: true
user_directory:
  enabled: true
stats:
   enabled: true
   bucket_size: 1d
   retention: 1y
enable_room_list_search: true
opentracing:
instance_map:
  w1:
    host: localhost
    port: 9034
redis:
  enabled: true
  host: /run/redis/redis.sock
```

worker config:
```
worker_app: synapse.app.generic_worker
worker_name: w1

# The replication listener on the main synapse process.
worker_replication_host: 127.0.0.1
worker_replication_http_port: 9093

worker_listeners:
 - type: http
   port: 8083
   resources:
     - names:
       - client
       - federation

worker_log_config: /etc/synapse/log_config_w1.yaml
```

The synapse error logs don't show anything
