### ISSUE TITLE
[meta] Good First Issue watchtower

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9486]
Context:
> <@anoadragon453> If you're up for it, and come across some that are perhaps too easy, or you just don't want to solve, would you mind flagging them and I can label them Good First Issue?

This is that issue, I'll add them in the following format:

```yaml
issue: #XXXX
e.s.t.: P3, T-Enhancement, (etc.)
comment: (Here is some extra comments and context to go with)
```

(`e.s.t.`/`est` is "extra suggested tags")
