### ISSUE TITLE
Migrating from old OIDC to new OIDC provider configuration breaks authentication for existing accounts

### ISSUE THREAD

**Issue by luilegeant** [matrix-org/synapse#9514]
### Description

When upgrading from Synapse 1.26.0 to 1.27.0 or 1.28.0 (I can't figure out when the issue came up) the configuration for the OIDC provider (keycloak in my case) was changed as instructed on the upgrade file in release notes.
Since then, when i try to log in from a new device, a new account is created, instead of heaving `@user:domain.tld` I get `@user1:domain.tld` (notice the 1).

### Steps to reproduce

- Setup synapse 1.26.0 with the "old" way of configuring the oidc provider.
- Log in with one of your new account (you user gets created `@user:domain.tld`)
- Update to synapse 1.27.0 or 1.28.0 (I forgot which requires the configuration to be changed) & adapt your oidc configuration
- Log in with the same credential on a new device (old device still have an old valid state, so they continue working).
- When confirmation prompt will be `@user1:domain.tld` (notice the 1).

Expected behaviour:

- I can continue logging in with the same credential without triggering the creation of a new account.

### Version information

Homeserver with the issue identified on:
- `matrix.luilegeant.com`
- `matrix.torquetum.eu`

 What version of Synapse is running?

- **Version**: `{"server_version":"1.28.0","python_version":"3.8.8"}`

- **Install method**:
docker (image see: https://hub.docker.com/r/matrixdotorg/synapse)

- **Platform**:
docker container running in swarm mode on Ubuntu Server 18.04 LTS behind a reverse proxy.

### Extra notes:

- Upon reading release notes and digging a little into the repository, I came upon this [note at Line 73](https://github.com/matrix-org/synapse/blob/0d81a6fa3e1dc832f56ed09805229b9089758ba5/synapse/config/oidc_config.py#L73).
Could it be linked, because the id changed from the old config style to the new one ?
- Second note: would the configuration attribute [described on line 129](https://github.com/matrix-org/synapse/blob/0d81a6fa3e1dc832f56ed09805229b9089758ba5/synapse/config/oidc_config.py#L129) resolve my issue (temporary fix)

**Comment by richvdh** [comment]
can you clarify how you've changed your Synapse OIDC configuration? What was it before, and what is it now?

The problem is almost certainly related to `idp_id`, but the old style of config should work fine with no changes.

**Comment by luilegeant** [comment]
#### Complementary note:
I've made a mistake, its not 1.26.0 configuration style but **1.25.0** (although I've changed only when switching from 1.26.0 upward and needed to login when I was already on 1.28.0).

#### Case 1: reverting to old style configuration (element-web not happy)
My old configuration was (recomposition, I don't have a backup that old):
```yaml
oidc_config:
    enable: true
    issuer: "myissueruri"
    client_id: "synapse"
    client_secret: "mysecret"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.given_name }}"
```
If I try using the above configuration element web (1.21.0) on my synapse (1.28.0) and element-web says _"This homeserver doesn't offer any login flows which are supported by this client."_

#### Case 2: using new style configuration (creates new user)
The new configuration:
```yaml
oidc_providers:
  - idp_id: keycloak
    idp_name: "A fancy name"
    issuer: "myissueruri"
    client_id: "synapse"
    client_secret: "mysecret"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.given_name }}"
```
This is the case described above in the head of the ticket.
