### ISSUE TITLE
Improve the listener example on the metrics documentation

### ISSUE THREAD

**Issue by mahdi1234** [matrix-org/synapse#9955]
I'm pretty new to synapse setup, but I guess documentation is mainly for inexperienced users.

Imo documentation https://github.com/matrix-org/synapse/blob/master/docs/metrics-howto.md about setting up metrics running locally is quite confusing as it suggests adding second listener, but then my server did not federate at all. After help in synapse room I finally made it work properly with config below for synapse 1.33

```
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']

    resources:
      - names: [client, federation]
        compress: false

  - port: 9000
    tls: false
    type: http
    x_forwarded: false
    bind_addresses: ['127.0.0.1']

    resources:
    - names: [metrics]
      compress: false

```

I suggest similar example is added to doc (of course polished to best practice) or at least mentioned not adding new listener section or adjusted so second listener actually works.
